<div class="page_list row">
	<div class="col-xs-8 col-md-10" style="padding-bottom:5px">
		<a href="<?php echo $wo['company']['url'];?>" data-ajax="?link1=timeline&u=<?php echo str_replace(" ", "_", $wo['company']['s_name']);?>">
			<span class="page_title"><?php echo $wo['company']['compname']; ?></span>
		</a>
		<div class="page_info">
			<ul>
				<li>
					View <?php echo $wo['company']['s_name']; ?>'s Live Quote, Qtrly Results, Fin Ratios, Bal Sheet, P&L and much more...
				</li>
				<li>
				<div style="color: #4d91ea;">
					<small>
						<?php if (!empty($wo['company']['scripcode'])):?>
						<span>BSE: <?php echo $wo['company']['scripcode']; ?></span>
						<?php endif; ?>
						<?php if (!empty($wo['company']['symbol'])):?>
						<span>NSE: <?php echo $wo['company']['symbol']; ?></span>
						<?php endif; ?>
						<?php if (!empty($wo['company']['ind_name'])):?>
						<span>Sector: <?php echo $wo['company']['ind_name']; ?></span>
						<?php endif; ?>
					</small>
				</div>
				</li>
			</ul>
		</div>
	</div>
</div>
