<div class="col-md-4">
            <?php echo Wo_LoadPage('charts/sidechart');?>
			<ul class="wow_content negg_padd list-unstyled" style="padding: 2px 0px;">
				<li class="list-group-item hidden"><?php echo $wo['lang']['rating']; ?></li>
				<li class="list-group-item">
					<span class="pull-left"> 
						<a data-ajax="?link1=timeline&u=<?php echo$wo['company_data']['page_name'];?>&type=rating" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' .$wo['company_data']['page_name'] . '&type=rating');?>"><b><?php echo $wo['lang']['rating'] ?></b></a>:
					</span>
					<span class="page-rating">
						<fieldset>
							<?php
							$rating = Wo_PageRating($wo['company_data']['id'], $wo['user']['user_id']);
							?>
							<input type="radio" id="star5" name="rating" value="5" />
							<label for="star5" class="rate-page" data-val="5">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating <= 5 && $rating > 4) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star4" name="rating" value="4" />
							<label for="star4" class="rate-page" data-val="4">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 4 && $rating > 3) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star3" name="rating" value="3" />
							<label for="star3" class="rate-page" data-val="3">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 3 && $rating > 2) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star2" name="rating" value="2" />
							<label for="star2" class="rate-page" data-val="2">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 2 && $rating > 1) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star1" name="rating" value="1" />
							<label for="star1" class="rate-page" data-val="1">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 1 && $rating > 0) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
						</fieldset>
						<span class="clear"></span>
					</span>
					<span><?php echo  number_format($wo['company_data']['rating'], 1, '.', ' '); ?></span>
				</li>
			</ul>
		<?php echo Wo_LoadPage('stock_quotes/Additional_Info')?>
		<?php if(!empty($wo['company_data']['page_description'])) {  ?>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd">
					<div class="wo_page_hdng_innr">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M21,6V8H3V6H21M3,18H12V16H3V18M3,13H21V11H3V13Z"></path></svg></span> <?php echo $wo['lang']['about']; ?>
					</div>
				</div>
				<p class="page-margin"><?php echo$wo['company_data']['page_description']?></p>
			</div>
		<?php } ?>
		<?php 
		$sidebar_ad = Wo_GetAd('sidebar', false);
		if (!empty($sidebar_ad)) {?>
			<ul class="list-group sidebar-ad">
				<?php echo $sidebar_ad; ?>
			</ul>
		<?php } ?>
		<?php echo Wo_LoadPage('footer/sidebar-footer')?>
	</div>
</div>

<div class="modal fade" id="report_page" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>
					<?php echo $wo['lang']['report_page']; ?>
				</h4>
			</div>
			<div class="modal-body">
				<textarea class="form-control" placeholder="Type text" dir="auto" rows="4" id="report-page-text-<?php echo$wo['company_data']['page_id']; ?>"></textarea>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></dfiv><div></div><div></div></div>
				<button type="button" class="btn btn-main btn-mat" id="report-page-button" onclick="Wo_ReportPage(<?php echo$wo['company_data']['page_id']; ?>,true)" >
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
					<?php echo $wo['lang']['send']; ?>
				</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="rate_page" role="dialog">
	<div class="modal-dialog wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['rate']; ?> <?php echo$wo['company_data']['page_title'];?></h4>
			</div>
			<div class="modal-body">
				<textarea class="form-control" placeholder="<?php echo $wo['lang']['your_review']; ?>" dir="auto" rows="5" id="rating_review"></textarea>
				<input type="hidden" id="rating_value" >
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button type="button" class="btn btn-main btn-mat" id="rate-page-button" onclick="Wo_RatePage()" ><?php echo $wo['lang']['save']; ?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade in" id="page_rated" role="dialog">
	<div class="modal-dialog">
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
          <?php echo $wo['lang']['page_rated']; ?>
        </p>
      </div>
    </div>
</div>