<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists middlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
					<span>
						<svg class="bi bi-chat-square-quote" width="1em" height="1em" viewBox="-2 -1 20 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v8a1 1 0 001 1h2.5a2 2 0 011.6.8L8 14.333 9.9 11.8a2 2 0 011.6-.8H14a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v8a2 2 0 002 2h2.5a1 1 0 01.8.4l1.9 2.533a1 1 0 001.6 0l1.9-2.533a1 1 0 01.8-.4H14a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd"></path>
                            <path d="M7.468 5.667c0 .92-.776 1.666-1.734 1.666S4 6.587 4 5.667C4 4.747 4.776 4 5.734 4s1.734.746 1.734 1.667z"></path>
                            <path fill-rule="evenodd" d="M6.157 4.936a.438.438 0 01-.56.293.413.413 0 01-.274-.527c.08-.23.23-.44.477-.546a.891.891 0 01.698.014c.387.16.72.545.923.997.428.948.393 2.377-.942 3.706a.446.446 0 01-.612.01.405.405 0 01-.011-.59c1.093-1.087 1.058-2.158.77-2.794-.152-.336-.354-.514-.47-.563z" clip-rule="evenodd"></path>
                            <path d="M11.803 5.667c0 .92-.776 1.666-1.734 1.666-.957 0-1.734-.746-1.734-1.666 0-.92.777-1.667 1.734-1.667.958 0 1.734.746 1.734 1.667z"></path>
                            <path fill-rule="evenodd" d="M10.492 4.936a.438.438 0 01-.56.293.413.413 0 01-.274-.527c.08-.23.23-.44.477-.546a.891.891 0 01.698.014c.387.16.72.545.924.997.428.948.392 2.377-.942 3.706a.446.446 0 01-.613.01.405.405 0 01-.011-.59c1.093-1.087 1.058-2.158.77-2.794-.152-.336-.354-.514-.469-.563z" clip-rule="evenodd"></path>
                        </svg>
                    </span>
                    Stock Quotes
					</div>
				</div>
			</div>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_menu">
						<ul class="list-unstyled">
							<li class="active" id="All"><a href="javascript:void(0);" onClick="changePage('All')">All</a></li>
							<li id="0-9"><a href="javascript:void(0);" onClick="changePage('0-9')">0-9</a></li>
							<li id="A"><a href="javascript:void(0);" onClick="changePage('A')">A</a></li>
							<li id="B"><a href="javascript:void(0);" onClick="changePage('B')">B</a></li>
							<li id="C"><a href="javascript:void(0);" onClick="changePage('C')">C</a></li>
							<li id="D"><a href="javascript:void(0);" onClick="changePage('D')">D</a></li>
							<li id="E"><a href="javascript:void(0);" onClick="changePage('E')">E</a></li>
							<li id="F"><a href="javascript:void(0);" onClick="changePage('F')">F</a></li>
							<li id="G"><a href="javascript:void(0);" onClick="changePage('G')">G</a></li>
							<li id="H"><a href="javascript:void(0);" onClick="changePage('H')">H</a></li>
							<li id="I"><a href="javascript:void(0);" onClick="changePage('I')">I</a></li>
							<li id="J"><a href="javascript:void(0);" onClick="changePage('J')">J</a></li>
							<li id="K"><a href="javascript:void(0);" onClick="changePage('K')">K</a></li>
							<li id="L"><a href="javascript:void(0);" onClick="changePage('L')">L</a></li>
							<li id="M"><a href="javascript:void(0);" onClick="changePage('M')">M</a></li>
							<li id="N"><a href="javascript:void(0);" onClick="changePage('N')">N</a></li>
							<li id="O"><a href="javascript:void(0);" onClick="changePage('O')">O</a></li>
							<li id="P"><a href="javascript:void(0);" onClick="changePage('P')">P</a></li>
							<li id="Q"><a href="javascript:void(0);" onClick="changePage('Q')">Q</a></li>
							<li id="R"><a href="javascript:void(0);" onClick="changePage('R')">R</a></li>
							<li id="S"><a href="javascript:void(0);" onClick="changePage('S')">S</a></li>
							<li id="T"><a href="javascript:void(0);" onClick="changePage('T')">T</a></li>
							<li id="U"><a href="javascript:void(0);" onClick="changePage('U')">U</a></li>
							<li id="V"><a href="javascript:void(0);" onClick="changePage('V')">V</a></li>
							<li id="W"><a href="javascript:void(0);" onClick="changePage('W')">W</a></li>
							<li id="X"><a href="javascript:void(0);" onClick="changePage('X')">X</a></li>
							<li id="Y"><a href="javascript:void(0);" onClick="changePage('Y')">Y</a></li>
							<li id="Z"><a href="javascript:void(0);" onClick="changePage('Z')">Z</a></li>
						</ul>
						<div class="dropdown order_by" style="margin-left: auto;">
					<svg class="dropdown-toggle" data-toggle="dropdown" role="button" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 30 16"><path fill="currentColor" d="M7,10L12,15L17,10H7Z" opacity="0.7"/></svg>
					<ul class="dropdown-menu dropdown-menu-right" role="button">
						<li class="order_all <?php echo ($wo['user']['order_posts_by'] == 0) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(0);">Hits</a></li>
						<li class="order_people <?php echo ($wo['user']['order_posts_by'] == 1) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(1);">Ratings</a></li>
					</ul>
				</div>
					</div>
				</div>
			</div>
			<div class="wo_my_pages">
				<div id='loaded'>
					<?php
						$wo['current_company_page'] = 0;
						$wo['emptiness'] = '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="-1 -1 24 14" style="padding: 0px 0px 5px 11px;">
						<path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v8a1 1 0 001 1h2.5a2 2 0 011.6.8L8 14.333 9.9 11.8a2 2 0 011.6-.8H14a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v8a2 2 0 002 2h2.5a1 1 0 01.8.4l1.9 2.533a1 1 0 001.6 0l1.9-2.533a1 1 0 01.8-.4H14a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd"></path>
						<path d="M7.468 5.667c0 .92-.776 1.666-1.734 1.666S4 6.587 4 5.667C4 4.747 4.776 4 5.734 4s1.734.746 1.734 1.667z"></path>
						<path fill-rule="evenodd" d="M6.157 4.936a.438.438 0 01-.56.293.413.413 0 01-.274-.527c.08-.23.23-.44.477-.546a.891.891 0 01.698.014c.387.16.72.545.923.997.428.948.393 2.377-.942 3.706a.446.446 0 01-.612.01.405.405 0 01-.011-.59c1.093-1.087 1.058-2.158.77-2.794-.152-.336-.354-.514-.47-.563z" clip-rule="evenodd"></path>
						<path d="M11.803 5.667c0 .92-.776 1.666-1.734 1.666-.957 0-1.734-.746-1.734-1.666 0-.92.777-1.667 1.734-1.667.958 0 1.734.746 1.734 1.667z"></path>
						<path fill-rule="evenodd" d="M10.492 4.936a.438.438 0 01-.56.293.413.413 0 01-.274-.527c.08-.23.23-.44.477-.546a.891.891 0 01.698.014c.387.16.72.545.924.997.428.948.392 2.377-.942 3.706a.446.446 0 01-.613.01.405.405 0 01-.011-.59c1.093-1.087 1.058-2.158.77-2.794-.152-.336-.354-.514-.469-.563z" clip-rule="evenodd"></path>
					</svg>' . 'No Stock Quotes to show' . '</div>';
						$companies = Wo_GetCompanies(0);
						if (count($companies) > 0) {
							foreach ($companies as $wo['company']) {
								echo Wo_LoadPage('stock_quotes/company-list');
							}
						} else {
							echo $wo['emptiness'];
						}
					?>
				<div class="clear"></div>
			</div>
				<nav>
					<ul class="pagination">
						<li class="page-item disabled" id="Previous">
						<a class="page-link" href="javascript:void(0);" onClick="previous(1)">
							<span aria-hidden="true">&laquo;</span>
							<span class="sr-only">Previous</span>
						</a>
						</li>
						<li class="page-item" id="First"><a class="page-link" href="javascript:void(0);" onClick="first(1, 'All')">1</a></li>
						<li class="page-item" id="Second"><a class="page-link" href="javascript:void(0);" onClick="second(2, 'All')" >2</a></li>
						<li class="page-item" id="Third"><a class="page-link" href="javascript:void(0);" onClick="third(3, 'All')">3</a></li>
						<li class="page-item" id="Next">
						<a class="page-link" href="javascript:void(0);" onClick="next(3)">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
						</li>
					</ul>
				</nav>
				</div>
		</div>
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>
<script>

	function previous(page_num=1, pageFilter="All"){
		$("#loaded").remove();
		if(page_num!==1){
			first_page_num = page_num - 1;
			second_page_num = page_num;
			third_page_num = page_num + 1;
			$('#First').html(`<a class="page-link" href="javascript:void(0);" onClick="first(` + first_page_num.toString() + `, '` + pageFilter +`')">` + first_page_num.toString() + `</a>`);
			$('#Second').html(`<a class="page-link" href="javascript:void(0);" onClick="second(` + second_page_num.toString() + `, '` + pageFilter +`')">` + second_page_num.toString() + `</a>`);
			$('#Third').html(`<a class="page-link" href="javascript:void(0);" onClick="third(` + third_page_num.toString() + `, '` + pageFilter +`')">` + third_page_num.toString() + `</a>`);
			$('#Previous').html(`<a class="page-link" href="javascript:void(0);" onClick="previous(` + first_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a>`);
			$('#Next').html(`<a class="page-link" href="javascript:void(0);" onClick="next(` + third_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a>`);
			$('#Next').removeClass('disabled');
			if(first_page_num===1){
				$('#Previous').addClass('disabled');
			};
			page_ = (page_num-1)*15;
			$.get(Wo_Ajax_Requests_File(), {f:'company_list', page_num: page_, page_filter: pageFilter}, function (data) {
			if (data.status == 200) {
				$(".wo_my_pages").prepend(`<div id="loaded">` + data.html_snippets + `</div>`);
			} else if (data.status == 400) {
				$(".wo_my_pages").prepend(`<div id="loaded"><?php
					echo $wo['emptiness'];
				?><div class="clear"></div></div>`);
			}
		  });
		} else{
			$.get(Wo_Ajax_Requests_File(), {f:'company_list', page_num: 1}, function (data) {
			if (data.status == 200) {
				$(".wo_my_pages").prepend(`<div id="loaded">` + data.html_snippets + `</div>`);
			} else if (data.status == 400) {
				$(".wo_my_pages").prepend(`<div id="loaded"><?php
					echo $wo['emptiness'];
				?><div class="clear"></div></div>`);
			}
		  });
		}
	}

	function next(page_num=3, pageFilter="All"){
		$("#loaded").remove();
        console.log(page_num);
		if(page_num!==461){
			first_page_num = page_num - 1;
			second_page_num = page_num;
			third_page_num = page_num + 1;
			$('#First').html(`<a class="page-link" href="javascript:void(0);" onClick="first(` + first_page_num.toString() + `, '` + pageFilter +`')">` + first_page_num.toString() + `</a>`);
			$('#Second').html(`<a class="page-link" href="javascript:void(0);" onClick="second(` + second_page_num.toString() + `, '` + pageFilter +`')">` + second_page_num.toString() + `</a>`);
			$('#Third').html(`<a class="page-link" href="javascript:void(0);" onClick="third(` + third_page_num.toString() + `, '` + pageFilter +`')">` + third_page_num.toString() + `</a>`);
			$('#Previous').html(`<a class="page-link" href="javascript:void(0);" onClick="previous(` + first_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a>`);
			$('#Next').html(`<a class="page-link" href="javascript:void(0);" onClick="next(` + third_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a>`);
			$('#Previous').removeClass('disabled');
			if(third_page_num===461){
				$('#Previous').addClass('disabled');
			};
			$.get(Wo_Ajax_Requests_File(), {f:'company_list', page_num: page_num, page_filter: pageFilter}, function (data) {
			if (data.status == 200) {
                console.log("hi");
				$(".wo_my_pages").prepend(`<div id="loaded">` + data.html_snippets + `</div>`);
			} else if (data.status == 400) {
				$(".wo_my_pages").prepend(`<div id="loaded"><?php
					echo $wo['emptiness'];
				?><div class="clear"></div></div>`);
			}
  		});
		};
	}

    function first(page_num=1, pageFilter="All"){
		$("#loaded").remove();
        console.log(page_num);
		if(page_num!==1){
			first_page_num = page_num - 1;
			second_page_num = page_num;
			third_page_num = page_num + 1;
			$('#First').html(`<a class="page-link" href="javascript:void(0);" onClick="first(` + first_page_num.toString() + `, '` + pageFilter +`')">` + first_page_num.toString() + `</a>`);
			$('#Second').html(`<a class="page-link" href="javascript:void(0);" onClick="second(` + second_page_num.toString() + `, '` + pageFilter +`')">` + second_page_num.toString() + `</a>`);
			$('#Third').html(`<a class="page-link" href="javascript:void(0);" onClick="third(` + third_page_num.toString() + `, '` + pageFilter +`')">` + third_page_num.toString() + `</a>`);
			$('#Previous').html(`<a class="page-link" href="javascript:void(0);" onClick="previous(` + first_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a>`);
			$('#Next').html(`<a class="page-link" href="javascript:void(0);" onClick="next(` + third_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a>`);
			if(first_page_num===1){
				$('#Previous').addClass('disabled');
			} else{
				$('#Previous').removeClass('disabled');
			};
			if(third_page_num===461){
				$('#Next').addClass('disabled');
			} else{
				$('#Next').removeClass('disabled');
			};
		}
		$.get(Wo_Ajax_Requests_File(), {f:'company_list', page_num: page_num, page_filter: pageFilter}, function (data) {
			if (data.status == 200) {
				$(".wo_my_pages").prepend(`<div id="loaded">` + data.html_snippets + `</div>`);
			} else if (data.status == 400) {
				$(".wo_my_pages").prepend(`<div id="loaded"><?php
					echo $wo['emptiness'];
				?><div class="clear"></div></div>`);
			}
  		});
	};

	function second(page_num=2, pageFilter="All"){
		$("#loaded").remove();
		first_page_num = page_num - 1;
		second_page_num = page_num;
		third_page_num = page_num + 1;
        console.log(page_num);
		$('#First').html(`<a class="page-link" href="javascript:void(0);" onClick="first(` + first_page_num.toString() + `, '` + pageFilter +`')">` + first_page_num.toString() + `</a>`);
		$('#Second').html(`<a class="page-link" href="javascript:void(0);" onClick="second(` + second_page_num.toString() + `, '` + pageFilter +`')">` + second_page_num.toString() + `</a>`);
		$('#Third').html(`<a class="page-link" href="javascript:void(0);" onClick="third(` + third_page_num.toString() + `, '` + pageFilter +`')">` + third_page_num.toString() + `</a>`);
		$('#Previous').html(`<a class="page-link" href="javascript:void(0);" onClick="previous(` + first_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a>`);
		$('#Next').html(`<a class="page-link" href="javascript:void(0);" onClick="next(` + third_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a>`);
		if(first_page_num===1){
			$('#Previous').addClass('disabled');
		} else{
			$('#Previous').removeClass('disabled');
		};
		if(third_page_num===461){
			$('#Next').addClass('disabled');
		} else{
			$('#Next').removeClass('disabled');
		};
		$.get(Wo_Ajax_Requests_File(), {f:'company_list', page_num: page_num, page_filter: pageFilter}, function (data) {
			if (data.status == 200) {
				$(".wo_my_pages").prepend(`<div id="loaded">` + data.html_snippets + `</div>`);
			} else if (data.status == 400) {
				$(".wo_my_pages").prepend(`<div id="loaded"><?php
					echo $wo['emptiness'];
				?><div class="clear"></div></div>`);
			}
  		});
	};

	function third(page_num=3, pageFilter="All"){
		$("#loaded").remove();
		first_page_num = page_num - 1;
		second_page_num = page_num;
		third_page_num = page_num + 1;
        console.log(page_num);
		$('#First').html(`<a class="page-link" href="javascript:void(0);" onClick="first(` + first_page_num.toString() + `, '` + pageFilter +`')">` + first_page_num.toString() + `</a>`);
		$('#Second').html(`<a class="page-link" href="javascript:void(0);" onClick="second(` + second_page_num.toString() + `, '` + pageFilter +`')">` + second_page_num.toString() + `</a>`);
		$('#Third').html(`<a class="page-link" href="javascript:void(0);" onClick="third(` + third_page_num.toString() + `, '` + pageFilter +`')">` + third_page_num.toString() + `</a>`);
		$('#Previous').html(`<a class="page-link" href="javascript:void(0);" onClick="previous(` + first_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a>`);
		$('#Next').html(`<a class="page-link" href="javascript:void(0);" onClick="next(` + third_page_num.toString() + `, '` + pageFilter +`')"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a>`);
		if(first_page_num===1){
			$('#Previous').addClass('disabled');
		} else{
			$('#Previous').removeClass('disabled');
		};
		if(third_page_num===461){
			$('#Next').addClass('disabled');
		} else{
			$('#Next').removeClass('disabled');
		};
		$.get(Wo_Ajax_Requests_File(), {f:'company_list', page_num: page_num, page_filter: pageFilter}, function (data) {
			if (data.status == 200) {
				$(".wo_my_pages").prepend(`<div id="loaded">` + data.html_snippets + `</div>`);
			} else if (data.status == 400) {
				$(".wo_my_pages").prepend(`<div id="loaded"><?php
					echo $wo['emptiness'];
				?><div class="clear"></div></div>`);
			}
  		});
	};

	function changePage(pageFilter="All"){
			$("#loaded").remove();
			$("li").removeClass("active");
			$('#' + pageFilter).addClass("active");
			$('#First').html(`<a class="page-link" href="javascript:void(0);" onClick="first(1, '` + pageFilter +`')">1</a>`);
			$('#Second').html(`<a class="page-link" href="javascript:void(0);" onClick="second(2, '` + pageFilter +`')">2</a>`);
			$('#Third').html(`<a class="page-link" href="javascript:void(0);" onClick="third(3, '` + pageFilter +`')">3</a>`);
			$('#Previous').html(`<a class="page-link" href="javascript:void(0);" onClick="previous(1, '` + pageFilter +`')"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a>`);
			$('#Next').html(`<a class="page-link" href="javascript:void(0);" onClick="next(3, '` + pageFilter +`')"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a>`);
			$.get(Wo_Ajax_Requests_File(), {f:'company_list', page_num: 1, page_filter: pageFilter}, function (data) {
				if (data.status == 200) {
					$(".wo_my_pages").prepend(`<div id="loaded">` + data.html_snippets + `</div>`);
				} else if (data.status == 400) {
					$(".wo_my_pages").prepend(`<div id="loaded"><?php
						echo $wo['emptiness'];
					?><div class="clear"></div></div>`);
				}
			});
	};

</script>
