<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var oa_to_not_add = new Array();
    var oa_num = 1;

    function AddOAToTable(){

        table_body_data_to_add = `<tr id="`+ oa_num +`" style="height:39px">
                                      <td><input id="oa_type" type="text" style="height:39px" /></td>
                                      <td><input id="oa_transaction_date" type="date" name="transaction_date"/></td>
                                      <td>
                                          <span class="stock_quote_transac_price_div">
                                              <input id="oa_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" />
                                          </span>
                                      </td>
                                      <td>
                                          <span class="stock_quote_transac_price_div">
                                              <input id="oa_current_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="current_price" style="height:39px;" />
                                          </span>
                                      </td>
                                      <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteOA(`+ oa_num +`)"></i></td>
                                  </tr>

                                  <tr id="`+ oa_num +`_charge" style="height:39px">
                                      <td colspan="5">
                                          <span class="small">Notes:</span>
                                          <br>
                                          <span>
                                              <textarea name="notes" id="notes" rows="1"></textarea>
                                          </span>
                                      </td>
                                  </tr>`


        oa_num += 1;

        $('#table_oa_quote_search_body').append(table_body_data_to_add);
    }

    function deleteOA(id){

        oa_to_not_add.push(id);

        console.log(oa_to_not_add);
        console.log(oa_to_not_add.length);
        console.log(oa_num);

        if (oa_to_not_add.length == oa_num){

            window.location.replace("<?php echo $wo['portfolio_data']['url'];?>");

        }else{

            $("#"+id).remove();
            $("#"+id+"_charge").remove();

        }
    }

    function pushOADataToBackend(){
        oa_array_to_send = new Array();

        /* console.log($("#"+oa_to_add[id]+id+"charge_").text()) */

        for (id = 0; id < oa_num; id++){
            if (!oa_to_not_add.includes(id)){

                if ($("#"+id+" #oa_transaction_date").val() === ""){
                    $("#"+id+" #oa_transaction_date").val("NaN");
                }
                console.log(parseFloat($("#"+id+"_charge #oa_transaction_net_amount").val()));

                oaInfo = {

                        oa_type: $('#'+id+' #oa_type').val(),
                        oa_transaction_date: parseInt(new Date($("#"+id+" #oa_transaction_date").val()).getTime()/1000),
                        oa_transaction_price: parseFloat($("#"+id+" #oa_transaction_price").val()),
                        oa_current_price: parseFloat($("#"+id+" #oa_current_price").val()),
                        note: $("#"+id+"_charge #notes").val(),

                            };

                oa_array_to_send.push(oaInfo);
            }
        }

        console.log(oa_array_to_send);

        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'add_oa',
                oa_array: oa_array_to_send,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        console.log(data);
                        console.log("done");
                        location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>';
                    }
                    else if (data['status'] == 401){
                        console.log(data['error']);
                        $('#oa_add_errors').text(data['error']);
                    }
                    else{
                        console.log(data);
                        $('#oa_add_errors').text(data['error']);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

</script>
