<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var oa_to_not_add = new Array();
    var oa_num = 1;

    function AddOAToTable(){

        table_body_data_to_add = `<tr id="`+ oa_num +`" style="height:39px">
                                      <td><input id="oa_type" type="text" style="height:39px" /></td>
                                      <td><input id="oa_transaction_date" type="date" name="transaction_date"/></td>
                                      <td>
                                          <span class="stock_quote_transac_price_div">
                                              <input id="oa_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" />
                                          </span>
                                      </td>
                                      <td>
                                          <span class="stock_quote_transac_price_div">
                                              <input id="oa_current_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="current_price" style="height:39px;" />
                                          </span>
                                      </td>
                                      <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteOA(`+ oa_num +`)"></i></td>
                                  </tr>

                                  <tr id="`+ oa_num +`_charge" style="height:39px">
                                      <td colspan="5">
                                          <span class="small">Notes:</span>
                                          <br>
                                          <span>
                                              <textarea name="notes" id="notes" rows="1"></textarea>
                                          </span>
                                      </td>
                                  </tr>`


        oa_num += 1;

        $('#table_oa_quote_search_body').append(table_body_data_to_add);
    }

    function deleteOA(id){

        oa_to_not_add.push(id);

        console.log(oa_to_not_add);
        console.log(oa_to_not_add.length);
        console.log(oa_num);

        if (oa_to_not_add.length == oa_num){

            window.location.replace("<?php echo $wo['portfolio_data']['url'];?>");

        }else{

            $("#"+id).remove();
            $("#"+id+"_charge").remove();

        }
    }

    function ajax_call_for_oa(oa_array_to_send, auto_add_){
        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'add_oa',
                oa_array: oa_array_to_send,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                auto_add: auto_add_,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        Swal.fire({
                            icon: 'success',
                            title: 'Other Assets Added Successfully!',
                        }).then((result) => {
                            localStorage.removeItem(<?php echo $wo['portfolio_data']['portfolio_id']; ?> + "_portfolio_assets");
                            location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>';
                        })
                    }
                    else if (data['status'] == 401){
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                    }
                    else{
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                        console.log(data['error']);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

    function pushOADataToBackend(){
        var oa_array_to_send = new Array();
        var oa_total_price   = 0;
        var earliest_oa_date = undefined;

        /* console.log($("#"+oa_to_add[id]+id+"charge_").text()) */

        for (id = 0; id < oa_num; id++){
            if (!oa_to_not_add.includes(id)){

                if ($("#"+id+" #oa_transaction_date").val() === ""){
                    $("#"+id+" #oa_transaction_date").val("NaN");
                }

                oa_total_price += parseFloat($("#"+id+" #oa_transaction_price").val());
                if((earliest_oa_date == undefined) || (parseInt(new Date($("#"+id+" #oa_transaction_date").val()).getTime()/1000) < earliest_property_date)) earliest_property_date = parseInt(new Date($("#"+id+" #property_transaction_date").val()).getTime()/1000);

                oaInfo = {

                        oa_type: $('#'+id+' #oa_type').val(),
                        oa_transaction_date: parseInt(new Date($("#"+id+" #oa_transaction_date").val()).getTime()/1000),
                        oa_transaction_price: parseFloat($("#"+id+" #oa_transaction_price").val()),
                        oa_current_price: parseFloat($("#"+id+" #oa_current_price").val()),
                        note: $("#"+id+"_charge #notes").val(),

                            };

                oa_array_to_send.push(oaInfo);
            }
        }

        console.log(oa_array_to_send);

        if (oa_total_price > <?php echo $wo['portfolio_data']['current_value_cash']; ?>){
            Swal.fire({
                title: '<p style="color: red;">Insufficient Cash Available</p>',
                text: 'Cash Available: ₹<?php echo $wo['portfolio_data']['current_value_cash']; ?> & Transaction Cost: ₹' + oa_total_price,
                width: 400,
                padding: '3em',
                showCancelButton: false,
                showCloseButton: true,
                showDenyButton: true,
                confirmButtonColor: 'green',
                denyButtonColor: '#236CB0',
                denyButtonText: 'Add Cash Automatically',
                confirmButtonText: 'Add Cash Manually',
                showLoaderOnConfirm: true,
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Add Cash Manually',
                        text: 'Minimum Amount To Add For This Transaction: ₹' + (oa_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>),
                        input: 'number',
                        inputAttributes: { min: (oa_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>), step: 0.01 },
                        validationMessage: 'Added amount is less than Required amount!',
                        showCloseButton: true,
                        showCancelButton: true,
                        confirmButtonText: 'Add',
                        preConfirm: (amount) => {
                            $.ajax({
                                url: Wo_Ajax_Requests_File(),
                                type: 'GET',
                                dataType: 'json',
                                data: {
                                    f:'add_cash_for_asset',
                                    cash: amount,
                                    portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                                    note: 'Manually added cash for buying Other Assets',
                                    date_: earliest_oa_date,
                                }
                            });
                        },
                        allowOutsideClick: () => !Swal.isLoading()
                    }).then((result) => {
                        if (result.isConfirmed) {
                            ajax_call_for_oa(oa_array_to_send, '0');
                        }
                    })
                } else if (result.isDenied) {
                    ajax_call_for_oa(oa_array_to_send, '1');
                }
            })
        } else {
            ajax_call_for_oa(oa_array_to_send, '0');
        }
    }

</script>
