<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var loans_to_not_add = new Array();
    var loans_num = 1;

    function AddLoansToTable(){

        table_body_data_to_add = `<tr id="` + loans_num + `" style="height:39px">
                                        <td><input id="loans_type" style="height:39px" type="text" name="loans_type"/></td>
                                        <td><input id="loans_bank" style="height:39px" type="text" name="loans_bank"/></td>
                                        <td width="7%">
                                            <span class="loans_transac_price_div">
                                                <input id="loans_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="width:100%; height:39px;" />
                                            </span>
                                        </td>
                                        <td><input id="loans_transaction_date" type="date" name="transaction_date" onkeyup=changeLoansValues(` + loans_num + `) onchange=changeLoansValues(` + loans_num + `) /></td>
                                        <td width="7%"><input id="loans_rate" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="loans_rate" style="width:100%; height:39px;" /></td>
                                        <td width="1%">
                                            <input style="width: 150%; height:39px" id="loans_yrs" min="0" value="0" name="loans_yrs" onkeyup=changeLoansValues(` + loans_num + `) onchange=changeLoansValues(` + loans_num + `) />
                                        </td>
                                        <td width="1%" style="padding-left:1%">
                                            <input style="width: 100%; height:39px" id="loans_mths" min="0" value="0" name="loans_mths" onkeyup=changeLoansValues(` + loans_num + `) onchange=changeLoansValues(` + loans_num + `) />
                                        </td>
                                        <td width="1%">
                                            <input style="width: 100%; height:39px" id="loans_days" min="0" value="0" name="loans_days" onkeyup=changeLoansValues(` + loans_num + `) onchange=changeLoansValues(` + loans_num + `) />
                                        </td>
                                        <td><input id="loans_maturity_date" type="date" name="loans_maturity_date" readonly /></td>
                                        <td><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteLoans(` + loans_num + `)"></i></td>
                                    </tr>`


        loans_num += 1;

        $('#table_loans_quote_search_body').append(table_body_data_to_add);
    }

    function changeLoansValues(id){
        var smallDaysMnths = [4, 6, 9, 11];
        var today = new Date($("#"+id+" #loans_transaction_date").val());
        days_increase = today.getDate() + parseInt($("#"+id+" #loans_days").val());
        mnths_increase = today.getMonth() + 1 + parseInt($("#"+id+" #loans_mths").val());
        yrs_increase = parseInt(today.getFullYear()) + parseInt($("#"+id+" #loans_yrs").val());

        if (days_increase > 31){
            mnths_increase += parseInt(days_increase / 31);
            days_increase = parseInt(days_increase % 31);
        }
        days_increase = ((days_increase == 0) ? 31 : days_increase);

        if (mnths_increase > 12){
            yrs_increase += parseInt(mnths_increase / 12);
            mnths_increase = parseInt(mnths_increase % 12);
        }
        mnths_increase =((mnths_increase == 0) ? 12 : mnths_increase);

        if (smallDaysMnths.includes(mnths_increase)){
            if (days_increase == 31){
                days_increase =  1;
                mnths_increase += 1;
            }
        } else if (mnths_increase == 2){
            var factor_to_check = ((yrs_increase % 4 == 0) ? 29 : 28);
            if (days_increase > factor_to_check){
                mnths_increase += 1;
                days_increase = parseInt(days_increase % factor_to_check);
            }
        }

        var dd = String(days_increase).padStart(2, '0');
        var mm = String(mnths_increase).padStart(2, '0'); //January is 0!
        var yyyy = String(yrs_increase);
        today = yyyy + '-' + mm + '-' + dd;
        $("#"+id+" #loans_maturity_date").val(today);

    }

    function deleteLoans(id){
        loans_to_not_add.push(id);

        if (loans_to_not_add.length == loans_num){

            window.location.replace("<?php echo $wo['portfolio_data']['url'];?>");

        }else{

            $("#"+id).remove();
            /* $("#"+id+"_charge").remove(); */

        }
    }

    function pushLoansDataToBackend(){
        loans_array_to_send = new Array();

        /* console.log($("#"+loans_to_add[id]+id+"charge_").text()) */

        for (id = 0; id < loans_num; id++){
            if (!loans_to_not_add.includes(id)){

                if ($("#"+id+" #loans_transaction_date").val() === ""){
                    $("#"+id+" #loans_transaction_date").val("NaN");
                }

                if ($("#"+id+" #loans_maturity_date").val() === ""){
                    $("#"+id+" #loans_maturity_date").val("NaN");
                }

                console.log(parseFloat($("#"+id+"_charge #loans_transaction_net_amount").val()));

                loansInfo = {

                        loans_type: $('#'+id+' #loans_type').val(),
                        loans_bank: $('#'+id+' #loans_bank').val(),
                        loans_transaction_price: parseFloat($("#"+id+" #loans_transaction_price").val()),
                        loans_transaction_date: parseInt(new Date($("#"+id+" #loans_transaction_date").val()).getTime()/1000),
                        loans_transaction_interest: parseFloat($("#"+id+" #loans_rate").val()),
                        loans_maturity_date: parseInt(new Date($("#"+id+" #loans_maturity_date").val()).getTime()/1000),

                            };

                loans_array_to_send.push(loansInfo);
            }
        }

        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'add_loans',
                loans_array: loans_array_to_send,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        console.log(data);
                        console.log("done");
                        localStorage.removeItem(<?php echo $wo['portfolio_data']['portfolio_id']; ?> + "_portfolio_assets");
                        location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>';
                    }
                    else if (data['status'] == 401){
                        console.log(data['error']);
                        $('#loans_add_errors').text(data['error']);
                    }
                    else{
                        console.log(data);
                        $('#loans_add_errors').text(data['error']);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

</script>
