<ul class="wow_content negg_padd list-unstyled event-options-list right_user_info" style="margin-top:0px; font-weight: bold;">
			<div class="wo_page_hdng">
				<div class="wo_page_hdng_innr">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path></svg></span> Additional <?php echo $wo['lang']['info']; ?>.
				</div>
			</div>
			<li class="list-group-item">
				Mkt Cap (Cr)<span class="pull-right" style="color: grey;">990,088.02</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				PE<span class="pull-right" style="color: grey;">32.04</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				PE(Cons)<span class="pull-right" style="color: grey;">25.16</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Book Value<span class="pull-right" style="color: grey;">669.75</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Face Value<span class="pull-right" style="color: grey;">10.00</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Price/Book (MRQ)<span class="pull-right" style="color: grey;">2.33</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Cash EPS<span class="pull-right" style="color: grey;">64.09</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				EPSc<span class="pull-right" style="color: grey;">48.75</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Price/Earning (TTM)<span class="pull-right" style="color: grey;">24.37</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Enterprise Val (Cr)<span class="pull-right" style="color: grey;">1,148,040</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">.02
				EV/EBITDA<span class="pull-right" style="color: grey;">17.29</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				EV/Sales<span class="pull-right" style="color: grey;">3.27</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Div Yield<span class="pull-right" style="color: grey;">0.42</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Mcap to Sales<span class="pull-right" style="color: grey;">2.82</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Price/Sales<span class="pull-right" style="color: grey;">0.00045</span>
			</li>
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<li class="list-group-item">
				Div
			</li>
		</ul>
