<script>

    function processGraphData(data, fincode_volume, fincode_sorted_dates, currentVal){

        var graphData = new Object();

        for (value_index in data) {
            var value = data[value_index];
            console.log('Val idx');
            console.log(value_index);
            console.log(value);

            var fincode = value['fincode'];

            var volume = fincode_volume[fincode][fincode_sorted_dates[fincode][0]];

            graphData[fincode] = {
                                    'Dates' : new Array(),
                                    'Prices': new Array(),
                                 };

            var date_index = 0;

            var last_day_modif = (fincode_sorted_dates[fincode].length > 1) ? false : true;
            console.log(fincode_sorted_dates[fincode]);
            var last_day_modif_idx = 0;

            if (last_day_modif === true){

                for (idx_ = last_day_modif_idx; idx_ < value.Table.length; idx_++){
                    var val = value.Table[idx_];

                    if (val['date'] < fincode_sorted_dates[fincode][0]){
                        continue;
                    }

                    graphData[fincode]['Dates'].push(val['date']);
                    /* graphData[fincode]['Prices'].push((currentVal - (volume * val['price']))); */
                    graphData[fincode]['Prices'].push((volume * val['price']));
                }

                console.log('Graph Data:');
                console.log(graphData);

            } else {
                for (val_idx in value.Table) {
                    var val = value.Table[val_idx];

                    if (val['date'] < fincode_sorted_dates[fincode][0]){
                        continue;
                    }
                    console.log('val');
                    console.log(val);

                    if (val['date'] > fincode_sorted_dates[fincode][date_index + 1]){

                        volume += fincode_volume[fincode][fincode_sorted_dates[fincode][date_index + 1]];

                        if (date_index < (fincode_sorted_dates[fincode].length - 2)) {
                            date_index += 1;
                        } else {
                            last_day_modif = true;
                            last_day_modif_idx = val_idx;
                            date_index = (fincode_sorted_dates[fincode].length - 1);
                            break;
                        }
                    }

                    graphData[fincode]['Dates'].push(val['date']);
                    /* graphData[fincode]['Prices'].push((currentVal - (volume * val['price']))); */
                    graphData[fincode]['Prices'].push((volume * val['price']));

                    console.log('Graph Data:');
                    console.log(graphData);
                };
            };
        };

        console.log(graphData);
        return graphData;
    };

    function getGraphData(fincode_data, fincode_volume, fincode_sorted_dates, currentVal, timeline, all_dates = new Array()) {

        console.log('Graph Argument Data:');
        console.log('Fincode Data:');
        console.log(fincode_data);
        console.log('Fincode Volume:');
        console.log(fincode_volume);
        console.log('Fincode Sorted Dates:');
        console.log(fincode_sorted_dates);
        console.log('Current Value:');
        console.log(currentVal);
        console.log('Timeline:');
        console.log(timeline);

        var graphData = new Object();
        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            /* async: false, */
            async: true,
            dataType: 'json',
            data: {
                f:'historical_data_cache',
                timeline: timeline,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
            },
                })
                .done(function(ajax_data) {
                    data = ajax_data.stock_data;
                    console.log('data');
                    console.log(data);
                    graphData = processGraphData(data, fincode_volume, fincode_sorted_dates, currentVal);
                    console.log('graphData:');
                    console.log(graphData);
                    if (document.getElementById("SA_myAreaChart")) stocksAreaChart(graphData, all_dates);
                });
    };

</script>
