<script>console.log('<?php echo json_encode($wo['portfolio_data']); ?>')</script>
<?php if ($wo['portfolio_data']['no_of_stocks'] > 0) { ?>

    <?php echo Wo_LoadPage('portfolio/dashboard_portfolio'); ?>

<?php } else { ?>

    <div style="background-color: white; display:flex; height: 93.5vh; width: 100%; justify-content: center; align-items: center; text-align: center; border-radius: 3px; margin-bottom:0px;">
        <div class="container" style="display: inline-block;">

            <div class="row" >
                <div class="col-md-12">
                    <div class="title" style="margin: 0; font-weight: 700; color: #3e3e3e; text-transform: capitalize;font-size:3em">
                        No Stocks found in <?php echo (strpos(strtolower($wo['portfolio_data']['portfolio_name']), 'portfolio') !== false) ? $wo['portfolio_data']['portfolio_name'] : 'Portfolio - ' . $wo['portfolio_data']['portfolio_name']; ?>

                        <script>
                            console.log(<?php echo json_encode($wo['portfolio_data']); ?>);
                        </script>

                    </div>
                </div>
            </div>

            <div class="row">

                <div id="stock_container" class="col-md-12">
                    <div class="stock_dropdown stock-search-container">

                        <div id="first_stock_add" class="stock_search" role="search">

                            <span class="stock_tooltip" data-toggle="tooltip" data-placement="bottom" title="Search and add Stocks">
                                <input class="stock_input" data-toggle="stock_dropdown" type="text" onkeyup="Wo_StockSearchResult(this.value)">
                            </span>

                            <span id="stock_document_import_upload">
                                |
                                <span class="stock_document_import" data-toggle="tooltip" data-placement="bottom" title="Import or Upload Portfolio"></span>
                            </span>

                        </div>

                        <div class="stock-quote-dropdown-menu search-dropdown-container" style="display:inline-block;left:auto;margin-top: 10px;margin-left: -6.4%;width: auto;" role="menu">
                          <div class="stock-search-dropdown-result"></div>
                        </div>

                    </div>
                </div>

                <div id="stock_quote_table_search" class="col-md-12 hidden">
                   <table class="table table-hover table-striped">

                       <thead>
                           <tr>
                               <th style="text-align: center;">Stock Name</th>
                               <th style="text-align: center;">Transaction Date</th>
                               <th style="text-align: center;">Transaction Price</th>
                               <th style="text-align: center;">Quantity</th>
                               <th style="text-align: center;">Action</th>
                           </tr>
                       </thead>

                       <tbody id="table_stock_quote_search_body"></tbody>

                   </table>

                   <span class="stock_search_submit" data-toggle="tooltip" data-placement="bottom" onclick="pushStockDataToBackend()" title="Add Stocks to Portfolio"></span>

                   <div class="stock_dropdown stock-search-container" style="float: left;">

                       <div id="extra_stock_seaches" class="stock_search" role="search">

                           <span class="stock_tooltip" data-toggle="tooltip" data-placement="bottom" title="Search and add Stocks">
                               <input class="stock_input" data-toggle="stock_dropdown" type="text" onkeyup="Wo_StockSearchResult(this.value)">
                           </span>

                       </div>

                       <div class="stock-quote-dropdown-menu search-dropdown-container" style="display:inline-block;left:auto;margin-top: 10px;margin-left: -6.3%;width: auto;" role="menu">
                         <div class="stock-search-dropdown-result"></div>
                       </div>

                   </div>

                </div>

            </div>

        </div>
    </div>

<?php }; ?>

<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0,10);
    });

    var StockSearchContainer = $('.stock-search-container');
    var StockSearchResult = $('.stock-search-dropdown-result');
    var stock_quotes_to_add = new Array();

    function Wo_StockSearchResult(query) {
        if (query != '') {
            Wo_progressIconLoader(StockSearchContainer.find('.stock_search'));
            StockSearchContainer.addClass('open');
            $.get(Wo_Ajax_Requests_File(), {f: 'search', s: 'stock_quote', query: query}, function(data) {
                if (data.status == 200) {
                    if (data.html.length == 0) {
                        StockSearchResult.html('<span class="center-text">' + " <?php echo $wo['lang']['no_result']; ?>" + '<span>');
                    } else {
                        StockSearchResult.html(data.html);
                    }
                }
                Wo_progressIconLoader(StockSearchContainer.find('#stock_search'));
            });
            $(document).click(function() {
                StockSearchContainer.removeClass('open');
            });
        } else {
            StockSearchContainer.removeClass('open');
        }
    }

    function AddStockToTable(fincode, comp_name){
        if (!stock_quotes_to_add.length){
            $('#stock_container').addClass('hidden');
            $('#stock_quote_table_search').removeClass('hidden');
        }
        table_body_data_to_add = `<tr id=`+ fincode +` style="height:39px">
                                     <td id="stock_name" class="stock_quote_name_search">` + comp_name + `</td>
                                     <td><input id="stock_transaction_date" type="date" name="transaction_date" /></td>
                                     <td>
                                         <span class="stock_quote_transac_price_div">
                                             <input id="stock_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" />
                                         </span>
                                     </td>
                                     <td><input id="stock_qty" type="number" min="0" value="0" step="any" name="quantity" style="height:39px;" /></td>
                                     <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteStockQuoteFromSearch(`+ fincode +`)"></i></td>
                                  </tr>`;

        stock_quotes_to_add.push(fincode);

        $('#table_stock_quote_search_body').append(table_body_data_to_add);
    }

    function deleteStockQuoteFromSearch(fincode){
        stock_quotes_to_add.splice(stock_quotes_to_add.indexOf(fincode), 1);
        if (!(stock_quotes_to_add.length)){
            $('#stock_container').removeClass('hidden');
            $('#stock_quote_table_search').addClass('hidden');
        }
        console.log(stock_quotes_to_add.length);
        $("#"+fincode).remove();
    }

    function pushStockDataToBackend(){
        var stock_array_to_send = new Array();

        stock_quotes_to_add.forEach(function (fincode, index_stock){
            if ($("#"+fincode+" #stock_transaction_date").val() === ""){
                $("#"+fincode+" #stock_transaction_date").val(new Date().toDateInputValue());
            }

            stockInfo = {

                    stock_fincode: parseInt(fincode),
                    stock_transaction_date: new Date($("#"+fincode+" #stock_transaction_date").val()).getTime()/1000,
                    stock_transaction_price: parseFloat($("#"+fincode+" #stock_transaction_price").val()),
                    stock_transaction_qty: parseFloat($("#"+fincode+" #stock_qty").val())

                        };

            //console.log(stockInfo);
            stock_array_to_send.push(stockInfo);
        });

        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'portfolio_data',
                stock_array: stock_array_to_send,
                no_of_stocks: stock_array_to_send.length,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        console.log(data);
                        history.go(0);
                    }
                    else{
                        console.log(data);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

</script>
