<script>console.log('<?php echo json_encode($wo['portfolio_data']); ?>')</script>
<?php if ($wo['portfolio_data']['total_invested_value'] > 0) { ?>

    <?php echo Wo_LoadPage('portfolio/dashboard_portfolio'); ?>

<?php } else { ?>

    <div style="background-color: white; display:flex; height: 93.5vh; width: 100%; justify-content: center; align-items: center; text-align: center; border-radius: 3px; margin-bottom:0px;">
        <div class="container" style="display: inline-block;">

            <div class="row" >
                <div class="col-md-12">
                    <div class="title" style="margin: 0; font-weight: 700; color: #3e3e3e; text-transform: capitalize;font-size:3em">
                        No Assets found in <?php echo (strpos(strtolower($wo['portfolio_data']['portfolio_name']), 'portfolio') !== false) ? $wo['portfolio_data']['portfolio_name'] : 'Portfolio - ' . $wo['portfolio_data']['portfolio_name']; ?>

                        <script>
                            console.log(<?php echo json_encode($wo['portfolio_data']); ?>);
                        </script>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="display: flex; justify-content: center; font-size: 1.5em;">

                    <table>
                        <th style="padding: 1em;"><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-stocks">Add Stocks</th>
                        <th style="padding: 1em;"><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-mutual-funds">Add Mutual Funds</th>
                        <th style="padding: 1em;"><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-bullion">Add Bullion</th>
                        <th style="padding: 1em;"><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-cash">Add Cash</th>
                        <th style="padding: 1em;"><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-FD">Add Fixed Deposit</th>
                        <th style="padding: 1em;"><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-property">Add Property</th>
                        <th style="padding: 1em;"><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-OA">Add Other Assets</th>
                    </table>

                </div>
            </div>

        </div>
    </div>

<?php }; ?>
