<table style="text-align: center;" class="table table-bordered table-striped">

    <thead class="SA_card-header SA_py-3">
        <tr>
            <th class="SA_text-primary"><span style="margin: 0.75em;">Particulars</span></th>
            <th style="text-align: center;" class="SA_text-primary">Invested Value</th>
            <th style="text-align: center;" class="SA_text-primary">Day's Gain</th>
            <th style="text-align: center;" class="SA_text-primary">Unrealised Gain</th>
            <th style="text-align: center;" class="SA_text-primary">Realised Gain</th>
            <th style="text-align: center;" class="SA_text-primary">Current Value</th>
        </tr>
    </thead>

    <tbody>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Stocks</span></th>
            <td>21</td>
            <td>234</td>
            <td>234</td>
            <td>23523</td>
            <td>2352</td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Mutual Funds</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Day's Gain</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Bullion</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Fixed Income</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Property</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Cash</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Xyz</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <th scope="row"><span style="margin: 0.75em;">Loans</span></th>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

    </tbody>

</table>
