<script>console.log(<?php echo json_encode($wo); ?>);</script>
<div class="row page-margin wo_page_profile" data-page="portfolio" data-id="<?php echo $wo['portfolio_data']['portfolio_name'];?>">
    <div class="profile-container">
		<div class="page-info-cont" style="margin-bottom: 0px !important;">
            <div class="row">
                <div class="col-xs-12 col-sm-9 col-md-8 first_row">
                    <div class="info">
                        <!-- <div class="title dropdown dropdown-toggle" type="button" id="menu1" data-toggle="dropdown" style="margin: 0;cursor: pointer;"> -->
                        <div class="title" style="margin: 0;">
                        <?php if ($wo['user']['portfolio_count'] > 1){ ?>
                            <span class="dropdown dropdown-toggle" type="button" id="menu1" data-toggle="dropdown" style="margin: 0;cursor: pointer;">
                                <a style="font-size: 50px;"><?php echo $wo['portfolio_data']['portfolio_name']; ?></a>
                                <i class="fa fa-caret-down fa-2x" style="color:#2E59D9"></i>
                            </span>

                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                                <?php
                                    $portfolios = Wo_GetPortfolioDropdown();
                                    foreach ($portfolios as $wo['portfolio_dropdown']) {
                                        if ($wo['portfolio_dropdown']['portfolio_url'] !== $wo['portfolio_data']['portfolio_url'])
                                            echo "<li role='presentation'><a style='font-size:13px;' role='menuitem' tabindex='-1' href='{$wo['portfolio_dropdown']['url']}'>{$wo['portfolio_dropdown']['portfolio_name']}</a></li>";
                                    }
                                ?>
                            </ul>
                        <?php } else {?>
                                <a style="font-size: 50px;"><?php echo $wo['portfolio_data']['portfolio_name']; ?></a>
                        <?php };?>

                                <span id="portfolio_eye" style="margin-left:2.3em;" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Toggle portfolio between private/public">
                                    <?php if ($wo['portfolio_data']['privacy_level'] < 3){?>
                                        <i style='cursor: pointer;' class="fa fa-eye fa-3x" onclick="SA_make_portfolio_private(true);"></i>
                                    <?php } else{?>
                                        <i style='cursor: pointer;' class="fa fa-eye-slash fa-3x" onclick="SA_make_portfolio_private(false);"></i>
                                    <?php };?>
                                </span>

                                <span style="margin-left:1em;" onclick="SA_SharePortfolioOn('<?php echo $wo['portfolio_data']['portfolio_url']; ?>')">
                                    <i style='cursor: pointer;' class="fa fa-share-alt fa-3x"></i>
                                </span>

                            </div>

                        <div class="small"><?php echo $wo['portfolio_data']['portfolio_description']; ?></div>

                    </div>
                </div>

                <span style="float: right;margin-top: 1.2%;margin-right: 1.2%;">
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=edit-stocks" class="SA_d-none SA-d-sm-inline_block SA_btn SA_btn-sm SA_shadow-sm" style="background-color: black;color: white;">Edit Stocks</a>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=add-stocks" class="SA_d-none SA-d-sm-inline_block SA_btn SA_btn-sm SA_shadow-sm" style="background-color: red;color: white;">Add Stocks</a>
                    <?php if ($wo['user']['portfolio_count'] > 2 && $wo['user']['is_pro'] == 0){ ?>
                        <a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>" class="SA_d-none SA-d-sm-inline_block SA_btn SA_btn-sm SA_btn-success SA_shadow-sm" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Upgrade to add more Portfolios">&nbsp;Upgrade to Pro</a>
                    <?php } else { ?>
                        <a href="<?php echo Wo_SeoLink('index.php?link1=create-portfolio');?>" class="SA_d-none SA-d-sm-inline_block SA_btn SA_btn-sm SA_btn-success SA_shadow-sm"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Add Portfolio</a>
                    <?php }; ?>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;t2=edit" class="SA_d-none SA-d-sm-inline_block SA_btn SA_btn-sm SA_btn-primary SA_shadow-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;Edit Portfolio</a>
                </span>

            </div>

            <div class="SA_row" style="margin-top: 1.5% !important;">

                <!-- Value -->
                <div class="SA_col-4">
                    <div class="SA_row">

                        <div class="SA_col-6">
                            <div class="SA_card SA_border-left-primary SA_shadow SA_h-100 SA_py-2">
                                <div class="SA_card-body">
                                    <div class="SA_row SA_no-gutters SA_align-items-center">
                                        <div class="SA_col SA_mr-2">
                                            <div class="SA_text-xs SA_font-weight-bold SA_text-primary SA_text-uppercase SA_mb-1">Current Value</div>
                                            <div class="SA_h5 SA_mb-0 SA_font-weight-bold SA_text-gray-800">&#8377;<span id='currentVal'>0</span></div>
                                        </div>
                                        <div class="SA_col-auto">
                                            <i class="fa fa-inr fa-2x SA_text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="SA_col-6">
                            <div class="SA_card SA_border-left-warning SA_shadow SA_h-100 SA_py-2">
                                <div class="SA_card-body">
                                    <div class="SA_row SA_no-gutters SA_align-items-center">
                                        <div class="SA_col SA_mr-2">
                                            <div class="SA_text-xs SA_font-weight-bold SA_text-warning SA_text-uppercase SA_mb-1">Invested Value</div>
                                            <div class="SA_h5 SA_mb-0 SA_font-weight-bold SA_text-gray-800">&#8377;<?php echo round($wo['portfolio_data']['total_invested_value'], 2); ?></div>
                                        </div>
                                        <div class="SA_col-auto">
                                            <i class="fa fa-inr fa-2x SA_text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="SA_col-4">
                    <div class="SA_row">

                       <!-- XIRR -->
                        <div class="SA_col-6">
                            <div class="SA_card SA_border-left-info SA_shadow SA_h-100">
                                <div class="SA_card-body">
                                    <div class="SA_row SA_no-gutters SA_align-items-center">

                                        <div class="SA_col SA_mr-2">
                                            <div class="SA_text-xs SA_font-weight-bold SA_text-info SA_text-uppercase SA_mb-1">XIRR</div>

                                            <div class="SA_row SA_no-gutters SA_align-items-center">
                                                <div class="SA_col-auto">
                                                    <div id="xirr_val" class="SA_h5 SA_mb-0 SA_mr-3 SA_font-weight-bold SA_text-gray-800">24</div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="SA_col-auto">
                                            <i class="fa fa-calculator fa-2x SA_text-gray-300"></i>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                       <!-- Overall Rank -->
                       <div class="SA_col-6">
                            <div class="SA_card SA_border-left-secondary SA_shadow SA_h-100 SA_py-2">
                                <div class="SA_card-body">
                                    <div class="SA_row SA_no-gutters SA_align-items-center">

                                        <div class="SA_col SA_mr-2">
                                          <div class="SA_text-xs SA_font-weight-bold SA_text-secondary SA_text-uppercase SA_mb-1">Overall Rank</div>
                                          <div class="SA_h5 SA_mb-0 SA_font-weight-bold SA_text-gray-800">1132</div>
                                        </div>

                                        <div class="SA_col-auto">
                                          <i class="fa fa-trophy fa-2x SA_text-gray-300"></i>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>


                <div class="SA_col-4">
                    <div class="SA_row">

                        <!-- Day's P&L -->
                        <div class="SA_col-6">
                            <div id="daily_p_p_l_div" class="SA_card SA_border-left-secondary SA_shadow SA_h-100">
                                <div class="SA_card-body">
                                    <div class="SA_row SA_no-gutters SA_align-items-center">

                                        <div class="SA_col SA_mr-2">
                                            <div id="daily_p_p_l_text" class="SA_text-xs SA_font-weight-bold SA_text-secondary SA_text-uppercase SA_mb-1">Day's P&amp;L:</div>

                                            <div class="SA_row SA_no-gutters SA_align-items-center">
                                                <div class="SA_col-auto">
                                                    <div class="SA_h5 SA_mb-0 SA_mr-3 SA_font-weight-bold SA_text-gray-800"><span style="font-size: 100%; font-weight: 700; color: #5a5c69;"> &nbsp;&#8377;<span id="daily_p_p_l">0</span></span><span style="font-size: small;">(<span id="daily_p_p_l_per">0</span>%)</span></div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="SA_col-auto">
                                            <i class="fa fa-inr fa-2x SA_text-gray-300"></i>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Overall P&L -->
                        <div class="SA_col-6">
                            <div id="overall_p_p_l_div" class="SA_card SA_border-left-secondary SA_shadow SA_h-100">
                                <div class="SA_card-body">
                                    <div class="SA_row SA_no-gutters SA_align-items-center">

                                        <div class="SA_col SA_mr-2">

                                            <div id="overall_p_p_l_text" class="SA_text-xs SA_font-weight-bold SA_text-secondary SA_text-uppercase SA_mb-1">Overall P&amp;L: </div>

                                            <div class="SA_row SA_no-gutters SA_align-items-center">
                                                <div class="SA_col-auto">
                                                      <div class="SA_h5 SA_mb-0 SA_mr-3 SA_font-weight-bold SA_text-gray-800"><span style="font-size: 100%; font-weight: 700; color: #5a5c69;"> &nbsp;&#8377;<span id="overall_p_p_l">0</span></span><span style="font-size: small;">(<span id="overall_p_p_l_per">0</span>%)</span></div>
                                                </div>
                                            </div>

                                        </div>

                                        <div class="SA_col-auto">
                                            <i class="fa fa-inr fa-2x SA_text-gray-300"></i>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

		</div>
	</div>
</div>

<div>

    <div class="row wo_user_profile" style="margin: -33px 0px 0px;">
        <label class="col-md-1 "></label>
        <div class="user-bottom-nav col-md-10" >
            <ul>

                <li>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>" data-ajax="<?php echo  $wo['portfolio_data']['raw_url'];?>" id="dashboard">
                        <span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z" fill="currentColor"></path></svg></span>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=overview&amp;content=stocks" data-ajax="<?php echo $wo['portfolio_data']['raw_url'];?>&amp;tab=overview&amp;content=stocks" id="overview">
                        <span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z" fill="currentColor"></path></svg></span>
                        <span>Overview</span>
                    </a>
                </li>

                <li>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=pro_analysis" data-ajax="<?php echo $wo['portfolio_data']['raw_url'];?>&amp;tab=pro_analysis" id="pro_analysis">
                        <span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z" fill="currentColor"></path></svg></span>
                        <span>Pro Analysis</span>
                    </a>
                </li>

                <li>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=performance" data-ajax="<?php echo $wo['portfolio_data']['raw_url'];?>&amp;tab=performance" id="performance">
                        <span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z" fill="currentColor"></path></svg></span>
                        <span>Performance</span>
                    </a>
                </li>

                <li>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=tax" data-ajax="<?php echo $wo['portfolio_data']['raw_url'];?>&amp;tab=tax" id="tax">
                        <span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z" fill="currentColor"></path></svg></span>
                        <span>Tax</span>
                    </a>
                </li>

                <li>
                    <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=transactions" data-ajax="<?php echo $wo['portfolio_data']['raw_url'];?>&amp;tab=transactions" id="transactions">
                        <span class="split-link"><?php echo $wo['portfolio_data']['no_of_unique_stocks']; ?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M11 4h10v2H11V4zm0 4h6v2h-6V8zm0 6h10v2H11v-2zm0 4h6v2h-6v-2zM3 4h6v6H3V4zm2 2v2h2V6H5zm-2 8h6v6H3v-6zm2 2v2h2v-2H5z" fill="currentColor"></path></svg></span>
                        <span>Transactions</span>
                    </a>
                </li>

            </ul>
        </div>
        <label class="col-md-1 "></label>
    </div>

<?php switch ($_GET['tab']) {
    case 'transactions': ?>

        <?php echo Wo_LoadPage('portfolio/stocks_in_portfolio_main'); ?>

<?php break;
    case 'other_assets': ?>

        <?php echo Wo_LoadPage('portfolio/stocks_in_portfolio_main'); ?>

<?php break;
    case 'equity': ?>

        <?php echo Wo_LoadPage('portfolio/stocks_in_portfolio_main'); ?>

<?php break;
    case 'mutual_funds': ?>

        <?php echo Wo_LoadPage('portfolio/stocks_in_portfolio_main'); ?>

<?php break;
    case 'overview': ?>

        <?php echo Wo_LoadPage('portfolio/overview_content'); ?>

<?php break;
    case 'tax': ?>

        <?php echo Wo_LoadPage('portfolio/tax_content'); ?>

<?php break;
    default: ?>

    <?php echo Wo_LoadPage('portfolio/dashboard_content'); ?>

<?php break;
    }; ?>

<?php echo Wo_LoadPage('portfolio/portfolioFunctions'); ?>
<?php echo Wo_LoadPage('portfolio/cacheAPI'); ?>
<?php echo Wo_LoadPage('portfolio/dashboard_js'); ?>
