<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script>

    function add_lineChart(dates_obj, type_dates_obj){
       console.log('Before');
       console.log(dates_obj);
       date_time_stamps = Object.keys(dates_obj).sort();
       var color_dict = new Object();
       var dates_array_to_send = new Array();
       var skip_end = false;

       color_dict[date_time_stamps[0]] = (dates_obj[date_time_stamps[0]] > 0) ? "green" : "red";

       for (tracking_point = 1; tracking_point < date_time_stamps.length; tracking_point++){
           color_dict[date_time_stamps[tracking_point]] = (dates_obj[date_time_stamps[tracking_point]] > 0) ? "green" : "red";
           dates_obj[date_time_stamps[tracking_point]] += dates_obj[date_time_stamps[tracking_point - 1]];
       };


       var current_date = parseInt(new Date().getTime()/1000);
       if (date_time_stamps[date_time_stamps.length - 1] != (current_date)) {
           skip_end = true;
           dates_obj[current_date] = dates_obj[date_time_stamps[date_time_stamps.length - 1]];
           color_dict[current_date] = 'gray';
           date_time_stamps.push(current_date);
       }

       var least_val = undefined;
       date_time_stamps.forEach(function (date_time){
           /* date_array_to_send = [parseInt(date_time) * 1000, dates_obj[date_time]]; */
           date_array_to_send = {x: parseInt(date_time) * 1000, y: dates_obj[date_time], color: color_dict[date_time]};
           dates_array_to_send.push(date_array_to_send);
           if ((dates_obj[date_time] < least_val) || least_val == undefined) least_val = dates_obj[date_time];
       });


       console.log('After');
       console.log(dates_obj);
       console.log(color_dict);
       console.log(type_dates_obj);
       ctx = document.querySelector("#asset_line_graph_SA");
       if (ctx) assetLineGraph(ctx, dates_array_to_send, least_val, date_time_stamps[0], type_dates_obj, skip_end, current_date);
    };

    function add_doughnutCharts(currentVal_array){
        /* ctx = document.getElementById("invested_val_allocation_SA"); */
        ctx = document.querySelector("#invested_val_allocation_SA");
        if (ctx) invested_value_allocation(ctx);
        /* var ctx = document.getElementById("current_val_allocation_SA"); */
        ctx = document.querySelector("#current_val_allocation_SA");
        if (ctx) current_value_allocation(ctx, currentVal_array);
    };

    $( document ).ready(function(){
        Chart.defaults.global.defaultFontColor = '#858796';


        // Bar Chart Example
        var ctx = document.getElementById("myBarChart");
        var myBarChart = new Chart(ctx, {
            type: 'horizontalBar',
            data: {
              labels: ["LTCG", "STCG"],
              datasets: [{
                  barThickness: 22,
                  data: [-238, -553],
                  backgroundColor: "#838383",
              },{
                  barThickness: 22,
                  data: [727, 589],
                  backgroundColor: "#1471cd",
              }],
            },
            options: {
                hover: {
                    animationDuration: 1,
                    mode: false
                },
                maintainAspectRatio: false,
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'month'
                        },
                        gridLines: {
                            display: false,
                            drawBorder: false
                        },
                        ticks: {
                            maxTicksLimit: 6
                        },
                        maxBarThickness: 25,
                        stacked: true,
                    }],
                    yAxes: [{
                        ticks: {
                            min: -1500,
                            max: 4500,
                            maxTicksLimit: 5,
                            padding: 10,
                        },
                        gridLines: {
                            color: "rgb(234, 236, 244)",
                            zeroLineColor: "rgb(234, 236, 244)",
                            drawBorder: false,
                            borderDash: [2],
                            zeroLineBorderDash: [2]
                        },
                        stacked: true,
                    }],
                },
                legend: {
                    display: false
                },
                tooltips: {
                    titleMarginBottom: 2,
                    titleFontSize: 14,
                    borderColor: '#dddfeb',
                    borderWidth: 1,
                    xPadding: 20,
                    displayColors: false,
                    intersect: false,
                    mode: 'index',
                    caretPadding: 10,
                    callbacks: {
                        label: function(tooltipItem, chart) {
                            /* console.log(tooltipItem); */
                            var datasetLabel = (tooltipItem.datasetIndex === 0) ? 'Unrealised' : 'Realised';
                            return datasetLabel + ': $' + (tooltipItem.xLabel);
                        }
                    }
                },
                animation: {
                    duration: 0,
                    onComplete: function () {
                        var chartInstance = this.chart,
                        ctx = chartInstance.ctx;
                        ctx.textAlign = 'center';
                        ctx.textBaseline = 'bottom';
                        this.data.datasets.forEach(function (dataset, i) {
                            var meta = chartInstance.controller.getDatasetMeta(i);
                            meta.data.forEach(function (bar, index) {
                                var data = dataset.data[index];
                                ctx.fillText(data, bar._model.x, bar._model.y - 12);
                            });
                        });
                    }
                }

            }
        });

        // Overall P&L Distribution
        var ctx = document.getElementById("Overall_PL");
        if (ctx){
            var myPieChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                        datasets: [{
                        data: [47, 33, 20],
                        backgroundColor: ['#1cc88a', '#e32d2d', '#787f8a'],
                        hoverBackgroundColor: ['#17a673', '#b81d1d', '#656970'],
                        hoverBorderColor: "rgba(234, 236, 244, 1)",
                    }],
                },
                options: {
                    maintainAspectRatio: false,
                    tooltips: {
                        backgroundColor: "rgb(255,255,255)",
                        bodyFontColor: "#858796",
                        borderColor: '#dddfeb',
                        borderWidth: 1,
                        xPadding: 15,
                        yPadding: 15,
                        displayColors: false,
                        caretPadding: 10,
                        callbacks: {
                            label: function(tooltipItem, data) {
                                var _labels = ["Profitable Stocks", "Loss-making Stocks", "Neutral Stocks"];
                                var dataset = data.datasets[tooltipItem.datasetIndex];
                                var currentValue = dataset.data[tooltipItem.index];
                                var _label = _labels[tooltipItem.index];

                                return _label + ": " + currentValue + "%";
                            }
                        },
                    },
                    legend: {
                        display: false
                    },
                    cutoutPercentage: 60,
                },
            });

            // Todays P&L Distribution
            var ctx = document.getElementById("Days_PL");
            var myPieChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                        datasets: [{
                        data: [52, 36, 12],
                        backgroundColor: ['#1cc88a', '#e32d2d', '#787f8a'],
                        hoverBackgroundColor: ['#17a673', '#b81d1d', '#656970'],
                        hoverBorderColor: "rgba(234, 236, 244, 1)",
                    }],
                },
                options: {
                    maintainAspectRatio: false,
                    tooltips: {
                        backgroundColor: "rgb(255,255,255)",
                        bodyFontColor: "#858796",
                        borderColor: '#dddfeb',
                        borderWidth: 1,
                        xPadding: 15,
                        yPadding: 15,
                        displayColors: false,
                        caretPadding: 10,
                        callbacks: {
                            label: function(tooltipItem, data) {
                                var _labels = ["Profitable Stocks", "Loss-making Stocks", "Neutral Stocks"];
                                var dataset = data.datasets[tooltipItem.datasetIndex];
                                var currentValue = dataset.data[tooltipItem.index];
                                var _label = _labels[tooltipItem.index];

                                return _label + ": " + currentValue + "%";
                            }
                        },
                    },
                    legend: {
                        display: false
                    },
                    cutoutPercentage: 60,
                },
            });

        }
    });

</script>
