<script>

const qtrly_graphs = [
                      'Net Sales', 'Total Expenditure', 'PBIDT (Excl OI)',
                      'Other Income', 'Operating Profit', 'Interest',
                      'PBDT', 'Depreciation', 'Profit Before Tax',
                      'Tax', 'Profit After Tax', 'Net Profit'
                     ];

const annual_graphs = [
                       'Net Sales', 'Total Expenditure', 'PBIDT (Excl OI)',
                       'Other Income', 'Operating Profit', 'Interest',
                       'Exceptional Items', 'Depreciation', 'Profit Before Tax',
                       'Tax', 'Profit After Tax', 'Reserves'
                      ];

const _financial_graphs = [
                           'Earnings Per Share (Rs)', 'CEPS(Rs)', 'DPS(Rs)',
                           'Book NAV/Share(Rs)', 'Tax Rate(%)', 'Margin Ratios',
                           'Core EBITDA Margin(%)', 'EBIT Margin(%)', 'Pre Tax Margin(%)',
                           'PAT Margin (%)', 'Cash Profit Margin (%)', 'Working Capital/Sales(x)'
                          ];

const profit_loss_graphs = [
                            'Gross Sales', 'Sales', 'Processing Charges / Service Income',
                            'Other Operational Income', 'Less: Excise Duty', 'Net Sales',
                            'Increase/Decrease in Stock', 'Raw Material Consumed', 'Opening Raw Materials',
                            'Purchases Raw Materials', 'Closing Raw Materials', 'Other Direct Purchases / Brought in cost'
                           ];

</script>