<table style="text-align: right; margin-bottom: 0em;" class="table table-bordered table-striped">

    <thead class="SA_card-header SA_py-3">
        <tr>
            <th class="SA_text-primary"><span style="margin: 0.75em;">Company</span></th>
            <th style="text-align: right;" class="SA_text-primary">CMP</th>
            <th style="text-align: right;" class="SA_text-primary">Qty<br><small>Avg Cost</small></th>
            <th style="text-align: right;" class="SA_text-primary">Days held</th>
            <th style="text-align: right;" class="SA_text-primary">Inv Value <br><small>Stock Weightage</small></th>
            <th style="text-align: right;" class="SA_text-primary">Days Gain<br><small>Change%</small></th>
            <th style="text-align: right;" class="SA_text-primary">Unrealised Gain<br><small>Change%</small></th>
            <th style="text-align: right;" class="SA_text-primary">Realised Gain</th>
            <th style="text-align: right;" class="SA_text-primary">Dividends</th>
            <th style="text-align: right;" class="SA_text-primary">Total Gains</th>
            <th style="text-align: right;" class="SA_text-primary">Current Value<br><small>Stock Weightage</small></th>
            <th style="text-align: right;" class="SA_text-primary">XIRR</th>
        </tr>
    </thead>

    <tbody id="overview_stocks_table_body"></tbody>

</table>
