<div class="portfolio_html" style="margin-top:1%">
    <div class="portfolio_body">
        <div id="SA_wrapper">

            <!-- Content Wrapper -->
            <div id="SA_content-wrapper" class="SA_d-flex SA_flex-column">

                <!-- Main Content -->
                <div id="SA_content">

                    <!-- Begin Page Content -->
                    <div class="SA_container-fluid">

                        <!-- Content Row -->
                        <div class="SA_row">

                            <!-- Pie Chart -->
                            <div class="SA_col-xl-6 SA_col-lg-6">
                                <div class="SA_row">

                                    <div class="SA_col-md-6 SA_mb-4">
                                       <div class="SA_card SA_shadow SA_mb-4">

                                            <!-- Card Header - Dropdown -->
                                            <div class="SA_card-header SA_py-3 SA_d-flex SA_flex-row SA_align-items-center SA_justify-content-between">
                                                <h6 class="SA_m-0 SA_font-weight-bold SA_text-primary">Day's P&L Distribution</h6>
                                            </div>

                                            <!-- Card Body -->
                                            <div class="SA_card-body" style="padding-bottom: 1.6em !important;">
                                                <div class="SA_row">

                                                    <div class="SA_col-6">
                                                        <div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                                                            <canvas id="Days_PL" style="display: block; width: 612px; height: 165px;" width="612" height="165" class="chartjs-render-monitor"></canvas>
                                                        </div>
                                                    </div>

                                                    <div class="SA_col-6">
                                                        <div style="margin-top:1.1em;margin-bottom:1.1em;">
                                                            <span style="font-size:110%;font-weight:650;">2 Stocks Gaining Today</span>
                                                            <br>
                                                            <span style="font-size:150%;font-weight:700;" class="SA_text-success">&#8377;7,250 (34%)</span>
                                                        </div>
                                                        <hr>
                                                        <div style="margin-top:1.1em;">
                                                            <span style="font-size:110%;font-weight:650;">1 Stock Losing Today</span>
                                                            <br>
                                                            <span style="font-size:150%;font-weight:700;" class="SA_text-danger">&#8377;500 (34%)</span>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="SA_col-md-6 SA_mb-4">
                                       <div class="SA_card SA_shadow SA_mb-4">

                                            <!-- Card Header - Dropdown -->
                                            <div class="SA_card-header SA_py-3 SA_d-flex SA_flex-row SA_align-items-center SA_justify-content-between">
                                                <h6 class="SA_m-0 SA_font-weight-bold SA_text-primary">Overall P&L Distribution</h6>
                                            </div>

                                            <!-- Card Body -->
                                            <div class="SA_card-body" style="padding-bottom: 1.6em !important;">
                                                <div class="SA_row">

                                                    <div class="SA_col-6">
                                                        <div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                                                            <canvas id="Overall_PL" style="display: block; width: 612px; height: 165px;" width="612" height="165" class="chartjs-render-monitor"></canvas>
                                                        </div>
                                                    </div>

                                                    <div class="SA_col-6">
                                                        <div style="margin-top:1.1em;margin-bottom:1.1em;">
                                                            <span style="font-size:110%;font-weight:650;">1 Stock Gaining Overall</span>
                                                            <br>
                                                            <span style="font-size:150%;font-weight:700;" class="SA_text-success">&#8377;34,164.33 (34%)</span>
                                                        </div>
                                                        <hr>
                                                        <div style="margin-top:1.1em;">
                                                            <span style="font-size:110%;font-weight:650;">2 Stocks Losing Overall</span>
                                                            <br>
                                                            <span style="font-size:150%;font-weight:700;" class="SA_text-danger">&#8377;55,005 (34%)</span>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>

                            <div class="SA_col-xl-6 SA_col-lg-6">
                                <div class="SA_row">

                                    <div class="SA_col-md-6 SA_mb-4">
                                        <div class="SA_card SA_shadow SA_mb-4">

                                            <!-- Card Header - Dropdown -->
                                            <div class="SA_card-header SA_py-3 SA_d-flex SA_flex-row SA_align-items-center SA_justify-content-between">
                                                <h6 class="SA_m-0 SA_font-weight-bold SA_text-primary">Tax</h6>
                                            </div>

                                            <!-- Card Body -->
                                            <div class="SA_card-body" style="padding-bottom: 0.6em !important;">
                                                <div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                                                    <canvas id="myBarChart" width="729" height="138" class="chartjs-render-monitor" style="display: block; width: 729px; height: 138px;"></canvas>
                                                </div>
                                            </div>

                                            <div class="SA_mb-4 SA_text-center SA_small">
                                                <span class="SA_mr-2">
                                                    <span style="margin-right:10%;"><i class="fa fa-circle" style="color: #838383;"></i> Unrealised</span>
                                                    <i class="fa fa-circle" style="color: #1471cd;"></i> Realised
                                                </span>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="SA_col-md-6 SA_mb-4">
                                        <div class="SA_card SA_shadow SA_mb-4">

                                            <!-- Card Header - Dropdown -->
                                            <div class="SA_card-header SA_py-3 SA_d-flex SA_flex-row SA_align-items-center SA_justify-content-between">
                                                <h6 class="SA_m-0 SA_font-weight-bold SA_text-primary">Tax</h6>
                                            </div>

                                            <!-- Card Body -->
                                            <div class="SA_card-body" style="padding-bottom: 0.6em !important;">
                                                <div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                                                    <canvas id="myBarChart" width="729" height="138" class="chartjs-render-monitor" style="display: block; width: 729px; height: 138px;"></canvas>
                                                </div>
                                            </div>

                                            <div class="SA_mb-4 SA_text-center SA_small">
                                                <span class="SA_mr-2">
                                                    <span style="margin-right:10%;"><i class="fa fa-circle" style="color: #838383;"></i> Unrealised</span>
                                                    <i class="fa fa-circle" style="color: #1471cd;"></i> Realised
                                                </span>
                                            </div>

                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>

                        <!-- Content Row -->
                        <div class="SA_row">
                             <!-- Content Column -->
                            <div class="SA_col-12 SA_mb-4">
                                 <!-- Extra Financial Data -->
                                 <div class="SA_card SA_shadow SA_mb-4">
                                    <?php echo Wo_LoadPage('portfolio/dashboard_table'); ?>
                                 </div>
                            </div>
                        </div>
                        <!-- /.SA_container-fluid -->

                    </div>
                    <!-- End of Main Content -->

                </div>
                <!-- End of Content Wrapper -->

            </div>
        </div>
    </div>

</div>
