<script>

    function findLocalItems(query) {
        var i, results = [];
        for (i in localStorage) {
            if (localStorage.hasOwnProperty(i)) {
                if (i.match(query) || (!query && typeof i === 'string')) {
                    value = JSON.parse(localStorage.getItem(i));
                    results.push(value);
                }
            }
        }
        return results;
    }

    function calculateTotalValsFD_display(data_of_all_fd, dates_obj, type_dates_obj, tab, content){

        var unrealized_currentVal = 0;
        var realized_currentVal = 0;
        var daysGain = 0;
        var unrealized_currentVal_individual = 0;
        var realized_currentVal_individual = 0;
        var no_of_days_individual = 0;
        var invested_fyr = 0;
        var unrealized_currentVal_fyr = 0;
        var realized_currentVal_fyr = 0;
        var unrealized_invested_val = 0;
        var realized_invested_val = 0;
        var financial_yr_timestamp  = new Date(new Date().getFullYear(), 3).getTime()/1000;

        data_of_all_fd.forEach(function (value) {

            no_of_days_individual = parseInt((parseInt(new Date().getTime()/1000) - value.transaction_date) / (60 * 60 * 24));
            no_of_days_individual = (no_of_days_individual == 0) ? 1 : no_of_days_individual;

            if (value.payout_type == "0"){
                unrealized_currentVal_individual = (parseFloat(value.transaction_price) * Math.pow((1 +
                    parseFloat(value.transaction_interest/100) /
                    parseInt(value.interest_payout_frequency)),
    (parseInt(value.interest_payout_frequency) * ( no_of_days_individual / 365))));

                daysGain   += (unrealized_currentVal_individual - parseFloat(value.transaction_price))/no_of_days_individual;
                unrealized_currentVal += unrealized_currentVal_individual;
                unrealized_invested_val += parseFloat(value.transaction_price);
            } else{
                realized_currentVal_individual = (parseFloat(value.transaction_price) * Math.pow((1 +
                    parseFloat(value.transaction_interest/100) /
                    parseInt(value.interest_payout_frequency)),
    (parseInt(value.interest_payout_frequency) * ( no_of_days_individual / 365))));

                daysGain   += (realized_currentVal_individual - parseFloat(value.transaction_price))/no_of_days_individual;
                realized_currentVal += realized_currentVal_individual;
                realized_invested_val += parseFloat(value.transaction_price);
            }


            console.log('Date from FD:');
            console.log(parseInt(value.transaction_date));
            if (parseInt(value.transaction_date) in dates_obj) dates_obj[parseInt(value.transaction_date)] += parseFloat(value.transaction_price);
            else dates_obj[parseInt(value.transaction_date)] = parseFloat(value.transaction_price);

            if (parseInt(value.transaction_date) in type_dates_obj){
                if ('Fixed Deposit' in type_dates_obj[parseInt(value.transaction_date)]) type_dates_obj[parseInt(value.transaction_date)]['Fixed Deposit'].push({'transaction_price': value.transaction_price, 'maturity_date': value.maturity_date, 'interest_rate': value.transaction_interest});
                else type_dates_obj[parseInt(value.transaction_date)]['Fixed Deposit'] = [{'transaction_price': value.transaction_price, 'maturity_date': value.maturity_date, 'interest_rate': value.transaction_interest}];
            } else {
                type_dates_obj[parseInt(value.transaction_date)] = {'Fixed Deposit': [{'transaction_price': value.transaction_price, 'maturity_date': value.maturity_date, 'interest_rate': value.transaction_interest}]}
            }

            if (parseInt(value.transaction_date) >= financial_yr_timestamp){
                unrealized_currentVal_fyr += unrealized_currentVal_individual;
                realized_currentVal_fyr += realized_currentVal_individual;
                invested_fyr += parseFloat(value.transaction_price);
            }


        });

        currentVal_toDisplay = parseFloat($('#currentVal').text()) + unrealized_currentVal;
        $('#currentVal').text(currentVal_toDisplay.toFixed(2));

        const daily_p_p_l = daysGain;
        $('#daily_p_p_l').text((parseFloat($('#daily_p_p_l').text()) + daily_p_p_l).toFixed(2));

        $('#total_assets').text(currentVal_toDisplay.toFixed(2));
        $('#total_current_value').text(currentVal_toDisplay.toFixed(2));

        $('#fd_currentValTable').text(((unrealized_currentVal) + realized_invested_val).toFixed(2));

        var invested_fyr_toDisplay = parseFloat($('#asset_added_this_year').text()) + invested_fyr;
        console.log('\n\n\n');
        console.log('invested_fyr_toDisplay');
        console.log(invested_fyr_toDisplay);
        $('#asset_added_this_year').text(invested_fyr_toDisplay.toFixed(2));

        var p_l_this_year = (unrealized_currentVal_fyr + realized_currentVal) - invested_fyr;
        var p_l_fyr_toDisplay = parseFloat($('#p_l_this_year').text()) + p_l_this_year;
        $('#p_l_this_year').text(p_l_fyr_toDisplay.toFixed(2));

        $('#fd_daily_p_p_lTable').text(daily_p_p_l.toFixed(2));

        const unrealized_overall_p_p_l = (unrealized_currentVal - unrealized_invested_val);
        $('#fd_overall_p_p_lTable_unrealised').text(unrealized_overall_p_p_l.toFixed(2));

        const realized_overall_p_p_l = (realized_currentVal - realized_invested_val);
        $('#fd_overall_p_p_lTable_realised').text(realized_overall_p_p_l.toFixed(2));

        $('#total_day_gain').text((parseFloat($('#total_day_gain').text()) + daysGain).toFixed(2));
        $('#total_unrealised_gain').text((parseFloat($('#total_unrealised_gain').text()) + unrealized_overall_p_p_l).toFixed(2));
        $('#total_realised_gain').text((parseFloat($('#total_realised_gain').text()) + realized_overall_p_p_l).toFixed(2));

        const overall_p_p_l_per_realised = (realized_invested_val == 0) ? 0 : (realized_overall_p_p_l / realized_invested_val) * 100;
        change_colors('fd_overall_p_p_lTable_realised', overall_p_p_l_per_realised);

        const overall_p_p_l_per_unrealised = (unrealized_invested_val == 0) ? 0 : (unrealized_overall_p_p_l / unrealized_invested_val) * 100;
        change_colors('fd_overall_p_p_lTable_unrealised', overall_p_p_l_per_unrealised);

        $('#fd_daily_p_p_lTable_text').removeClass('SA_text-secondary');
        $('#fd_daily_p_p_lTable_text').addClass('SA_text-success');

        return ((unrealized_currentVal) + realized_invested_val).toFixed(2);

    }

    function calculateTotalValsBullion_display(data_of_all_bullion, dates_obj, type_dates_obj){

        var currentVal = 0;
        var invested_fyr = 0;
        var financial_yr_timestamp  = new Date(new Date().getFullYear(), 3).getTime()/1000;

        data_of_all_bullion.forEach(function (value) {

            console.log('Date from Bullion:');
            console.log(parseInt(value.transaction_date));
            if (parseInt(value.transaction_date) in dates_obj) dates_obj[parseInt(value.transaction_date)] += parseFloat(value.net_amount);
            else dates_obj[parseInt(value.transaction_date)] = parseFloat(value.net_amount);

            if (parseInt(value.transaction_date) in type_dates_obj){
                if ('Bullion' in type_dates_obj[parseInt(value.transaction_date)]) type_dates_obj[parseInt(value.transaction_date)]['Bullion'].push(parseFloat(value.net_amount));
                else type_dates_obj[parseInt(value.transaction_date)]['Bullion'] = [parseFloat(value.net_amount)];
            } else {
                type_dates_obj[parseInt(value.transaction_date)] = {'Bullion': [parseFloat(value.net_amount)]};
            }

            if (parseInt(value.transaction_date) >= financial_yr_timestamp){
                invested_fyr += parseFloat(value.net_amount);
            }

        });

        var invested_fyr_toDisplay = parseFloat($('#asset_added_this_year').text()) + invested_fyr;
        $('#asset_added_this_year').text(invested_fyr_toDisplay.toFixed(2));
    }

    function calculateTotalValsCash_display(data_of_all_cash, dates_obj, type_dates_obj){

        var currentVal = 0;
        var invested_fyr = 0;
        var financial_yr_timestamp  = new Date(new Date().getFullYear(), 3).getTime()/1000;

        data_of_all_cash.forEach(function (value) {

            currentVal += parseFloat(value.transaction_amount);

            console.log('Date from Cash:');
            console.log(parseInt(value.transaction_date));
            if (parseInt(value.transaction_date) in dates_obj) dates_obj[parseInt(value.transaction_date)] += parseFloat(value.transaction_amount);
            else dates_obj[parseInt(value.transaction_date)] = parseFloat(value.transaction_amount);

            if (parseInt(value.transaction_date) in type_dates_obj){
                if ('Cash' in type_dates_obj[parseInt(value.transaction_date)]) type_dates_obj[parseInt(value.transaction_date)]['Cash'].push(parseFloat(value.transaction_amount));
                else type_dates_obj[parseInt(value.transaction_date)]['Cash'] = [parseFloat(value.transaction_amount)];
            } else {
                type_dates_obj[parseInt(value.transaction_date)] = {'Cash': [parseFloat(value.transaction_amount)]};
            }

            if (parseInt(value.transaction_date) >= financial_yr_timestamp){
                invested_fyr += parseFloat(value.transaction_amount);
            }

        });

        currentVal_toDisplay = parseFloat($('#currentVal').text()) + currentVal;
        $('#currentVal').text(currentVal_toDisplay.toFixed(2));
        $('#total_assets').text(currentVal_toDisplay.toFixed(2));
        $('#total_current_value').text(currentVal_toDisplay.toFixed(2));

        var invested_fyr_toDisplay = parseFloat($('#asset_added_this_year').text()) + invested_fyr;
        $('#asset_added_this_year').text(invested_fyr_toDisplay.toFixed(2));

        var p_l_this_year = 0;
        var p_l_fyr_toDisplay = parseFloat($('#p_l_this_year').text()) + p_l_this_year;
        $('#p_l_this_year').text(p_l_fyr_toDisplay.toFixed(2));
    }

    function calculateTotalValsOA_display(data_of_all_oa, dates_obj, type_dates_obj){

        var currentVal = 0;
        var currentVal_fyr = 0;
        var invested_fyr = 0;
        var financial_yr_timestamp  = new Date(new Date().getFullYear(), 3).getTime()/1000;

        data_of_all_oa.forEach(function (value) {

            currentVal += parseFloat(value.current_price);

            console.log('Date from OA:');
            console.log(parseInt(value.transaction_date));
            if (parseInt(value.transaction_date) in dates_obj) dates_obj[parseInt(value.transaction_date)] += parseFloat(value.transaction_price);
            else dates_obj[parseInt(value.transaction_date)] = parseFloat(value.transaction_price);

            if (parseInt(value.transaction_date) in type_dates_obj){
                if ('Other Assets' in type_dates_obj[parseInt(value.transaction_date)]) type_dates_obj[parseInt(value.transaction_date)]['Other Assets'].push(parseFloat(value.transaction_price));
                else type_dates_obj[parseInt(value.transaction_date)]['Other Assets'] = [parseFloat(value.transaction_price)];
            } else {
                type_dates_obj[parseInt(value.transaction_date)] = {'Other Assets': [parseFloat(value.transaction_price)]};
            }

            if (parseInt(value.transaction_date) >= financial_yr_timestamp){
                currentVal_fyr += parseFloat(value.current_price);
                invested_fyr += parseFloat(value.transaction_price);
            }

        });

        currentVal_toDisplay = parseFloat($('#currentVal').text()) + currentVal;
        $('#currentVal').text(currentVal_toDisplay.toFixed(2));
        $('#total_assets').text(currentVal_toDisplay.toFixed(2));
        $('#total_current_value').text(currentVal_toDisplay.toFixed(2));

        $('#oa_currentValTable').text(currentVal.toFixed(2));

        const overall_p_p_l = (currentVal - <?php echo $wo['portfolio_data']['invested_value_other_assets']; ?>);
        $('#overall_p_p_l').text((parseFloat($('#overall_p_p_l').text()) + overall_p_p_l).toFixed(2));
        $('#oa_overall_p_p_lTable').text(overall_p_p_l.toFixed(2));

        var invested_fyr_toDisplay = parseFloat($('#asset_added_this_year').text()) + invested_fyr;
        $('#asset_added_this_year').text(invested_fyr_toDisplay.toFixed(2));

        var p_l_this_year = currentVal_fyr - invested_fyr;
        var p_l_fyr_toDisplay = parseFloat($('#p_l_this_year').text()) + p_l_this_year;
        $('#p_l_this_year').text(p_l_fyr_toDisplay.toFixed(2));

        $('#total_unrealised_gain').text((parseFloat($('#total_unrealised_gain').text()) + overall_p_p_l).toFixed(2));

        const overall_p_p_l_per = (overall_p_p_l / <?php echo $wo['portfolio_data']['invested_value_other_assets']; ?>) * 100;
        change_colors('oa_overall_p_p_lTable', overall_p_p_l_per);

        return currentVal.toFixed(2);
    }

    function calculateTotalValsProperties_display(data_of_all_properties, dates_obj, type_dates_obj){

        var currentVal = 0;
        var currentVal_fyr = 0;
        var invested_fyr = 0;
        var financial_yr_timestamp  = new Date(new Date().getFullYear(), 3).getTime()/1000;

        data_of_all_properties.forEach(function (value) {

            currentVal += parseFloat(value.current_price);

            console.log('Date from properties:');
            console.log(parseInt(value.transaction_date));
            if (parseInt(value.transaction_date) in dates_obj) dates_obj[parseInt(value.transaction_date)] += parseFloat(value.transaction_price);
            else dates_obj[parseInt(value.transaction_date)] = parseFloat(value.transaction_price);

            console.log(parseFloat(value.transaction_price));
            if (parseInt(value.transaction_date) in type_dates_obj){
                if ('Properties' in type_dates_obj[parseInt(value.transaction_date)]) type_dates_obj[parseInt(value.transaction_date)]['Properties'].push(parseFloat(value.transaction_price));
                else type_dates_obj[parseInt(value.transaction_date)]['Properties'] = [parseFloat(value.transaction_price)];
            } else {
                type_dates_obj[parseInt(value.transaction_date)] = {'Properties': [parseFloat(value.transaction_price)]};
            }

            if (parseInt(value.transaction_date) >= financial_yr_timestamp){
                currentVal_fyr += parseFloat(value.current_price);
                invested_fyr += parseFloat(value.transaction_price);
            }

        });

        currentVal_toDisplay = parseFloat($('#currentVal').text()) + currentVal;
        $('#currentVal').text(currentVal_toDisplay.toFixed(2));
        $('#total_assets').text(currentVal_toDisplay.toFixed(2));
        $('#total_current_value').text(currentVal_toDisplay.toFixed(2));

        $('#properties_currentValTable').text(currentVal.toFixed(2));

        const overall_p_p_l = (currentVal - <?php echo $wo['portfolio_data']['invested_value_properties']; ?>);
        $('#overall_p_p_l').text((parseFloat($('#overall_p_p_l').text()) + overall_p_p_l).toFixed(2));
        $('#properties_overall_p_p_lTable').text(overall_p_p_l.toFixed(2));

        var invested_fyr_toDisplay = parseFloat($('#asset_added_this_year').text()) + invested_fyr;
        $('#asset_added_this_year').text(invested_fyr_toDisplay.toFixed(2));

        var p_l_this_year = currentVal_fyr - invested_fyr;
        var p_l_fyr_toDisplay = parseFloat($('#p_l_this_year').text()) + p_l_this_year;
        $('#p_l_this_year').text(p_l_fyr_toDisplay.toFixed(2));

        $('#total_unrealised_gain').text((parseFloat($('#total_unrealised_gain').text()) + overall_p_p_l).toFixed(2));

        const overall_p_p_l_per = (overall_p_p_l / <?php echo $wo['portfolio_data']['invested_value_properties'];?>) * 100;
        change_colors('properties_overall_p_p_lTable', overall_p_p_l_per);

        return currentVal.toFixed(2);
    }

    function calculateTotalValsMF_display(data_of_all_mutual_funds, dates_obj, type_dates_obj, tab, content){

        var oldVal                  = 0;
        var currentVal              = 0;
        var currentVal_fyr          = 0;
        var invested_fyr            = 0;
        var financial_yr_timestamp  = new Date(new Date().getFullYear(), 3).getTime()/1000;

        Object.keys(data_of_all_mutual_funds).forEach(function (scheme_code) {

            var total_qty_of_mf = 0;
            Object.keys(data_of_all_mutual_funds[scheme_code]['mf_portfolio_data']).forEach(function(date_time_stamp){
                total_qty_of_mf += data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_qty'];

                console.log('Date from mf:');
                console.log(parseInt(date_time_stamp));
                if (parseInt(date_time_stamp) in dates_obj) dates_obj[parseInt(date_time_stamp)] += parseFloat(data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_amount']);
                else dates_obj[parseInt(date_time_stamp)] = parseFloat(data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_amount']);

                if (parseInt(date_time_stamp) in type_dates_obj){
                    if ('Mutual Funds' in type_dates_obj[parseInt(date_time_stamp)]) type_dates_obj[parseInt(date_time_stamp)]['Mutual Funds'].push(parseFloat(data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_amount']));
                    else type_dates_obj[parseInt(date_time_stamp)]['Mutual Funds'] = [parseFloat(data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_amount'])];
                } else {
                    type_dates_obj[parseInt(date_time_stamp)] = {'Mutual Funds': [parseFloat(data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_amount'])]};
                }

                if (parseInt(date_time_stamp) >= financial_yr_timestamp){
                    currentVal_fyr += data_of_all_mutual_funds[scheme_code]['mf_data']['Net Asset Value'] * data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_qty'];
                    invested_fyr   += parseFloat(data_of_all_mutual_funds[scheme_code]['mf_portfolio_data'][date_time_stamp]['mf_transaction_amount']);
                }
            });

            currentVal += data_of_all_mutual_funds[scheme_code]['mf_data']['Net Asset Value'] * total_qty_of_mf;
            oldVal += data_of_all_mutual_funds[scheme_code]['mf_data']['Old Net Asset Value'] * total_qty_of_mf;

        });

        currentVal_toDisplay = parseFloat($('#currentVal').text()) + currentVal;
        $('#currentVal').text(currentVal_toDisplay.toFixed(2));

        const daily_p_p_l = (currentVal - oldVal);
        $('#daily_p_p_l').text((parseFloat($('#daily_p_p_l').text()) + daily_p_p_l).toFixed(2));

        const overall_p_p_l = (currentVal - <?php echo $wo['portfolio_data']['invested_value_mutual_funds']; ?>);
        $('#overall_p_p_l').text((parseFloat($('#overall_p_p_l').text()) + overall_p_p_l).toFixed(2));

        $('#total_assets').text(currentVal_toDisplay.toFixed(2));
        $('#total_current_value').text(currentVal_toDisplay.toFixed(2));

        $('#mf_currentValTable').text(currentVal.toFixed(2));

        $('#mf_daily_p_p_lTable').text(daily_p_p_l.toFixed(2));

        const daily_p_p_l_per = (daily_p_p_l / oldVal) * 100;
        change_colors('mf_daily_p_p_lTable', daily_p_p_l_per);

        $('#mf_overall_p_p_lTable').text(overall_p_p_l.toFixed(2));

        var invested_fyr_toDisplay = parseFloat($('#asset_added_this_year').text()) + invested_fyr;
        $('#asset_added_this_year').text(invested_fyr_toDisplay.toFixed(2));

        $('#total_day_gain').text((parseFloat($('#total_day_gain').text()) + daily_p_p_l).toFixed(2));
        $('#total_unrealised_gain').text((parseFloat($('#total_unrealised_gain').text()) + overall_p_p_l).toFixed(2));

        var p_l_this_year = currentVal_fyr - invested_fyr;
        var p_l_fyr_toDisplay = parseFloat($('#p_l_this_year').text()) + p_l_this_year;
        $('#p_l_this_year').text(p_l_fyr_toDisplay.toFixed(2));

        const overall_p_p_l_per = (overall_p_p_l / <?php echo $wo['portfolio_data']['invested_value_mutual_funds']; ?>) * 100;
        change_colors('mf_overall_p_p_lTable', overall_p_p_l_per);

        return currentVal.toFixed(2);
    }

    function calculateTotalValsStocks_display(data_of_all_stocks, dates_obj, type_dates_obj, tab, content){
        /* TODO Remove variables that are not needed */

        var num_of_trs               = 0;
        var currentVal               = 0;
        var num_loss_days            = 0;
        var total_loss_days          = 0;
        var num_profit_days          = 0;
        var num_loss_overall         = 0;
        var adjustedValTotal         = 0;
        var total_profit_days        = 0;
        var num_profit_overall       = 0;
        var total_loss_overall       = 0;
        var asset_sold_this_year     = 0;
        var total_profit_overall     = 0;
        var overview_daily_p_p_l     = 0;
        var asset_added_this_year    = 0;
        var overview_overall_p_p_l   = 0;
        var currentVal_of_asset_fyr  = 0;
        var today_max                = 0;
        var today_min                = 0;
        var overall_max              = 0;
        var overall_min              = 0;
        var today_max_per            = 0;
        var today_min_per            = 0;
        var overall_max_per          = 0;
        var overall_min_per          = 0;
        var today_max_comp           = '-';
        var today_min_comp           = '-';
        var overall_max_comp         = '-';
        var overall_min_comp         = '-';

        var loss_fincode             = new Array();
        var profit_fincode           = new Array();

        var fincode_stock_weightage_invested    = new Object();
        var fincode_sector_weightage_invested   = new Object();
        var fincode_mcap_weightage_invested     = new Object();
        var fincode_stock_weightage_current     = new Object();
        var fincode_sector_weightage_current    = new Object();
        var fincode_sector_weightage_profit     = new Object();
        var fincode_sector_weightage_profit_per = new Object();
        var fincode_mcap_weightage_current      = new Object();

        var fincode_added_this_fyr  = new Object();
        var financial_yr_timestamp  = new Date(new Date().getFullYear(), 3).getTime()/1000;

        data_of_all_stocks.forEach(function (value) {

            total_volume_of_stock  = 0;
            total_inv_val_of_stock = 0;
            current_val_of_stock   = 0;
            adjusted_val_of_stock  = 0;
            days_held_of_stock     = [];

            value.stock_portfolio_data.forEach(function(val) {

                console.log('Date from stocks:');
                console.log(parseInt(val.stock_transaction_date));

                total_inv_val_of_stock += (val.stock_transaction_price * val.stock_transaction_qty) + parseFloat(val.Charges);
                days_held_of_stock.push(Math.round(((new Date())-(val.stock_transaction_date*1000))/(1000*60*60*24)));

                if (tab == 'overview' && content == 'stocks'){
                    overview_overall_p_p_l = (value.price_detail_intraday == null) ? ((parseFloat(value.price_detail_adjusted.close) * parseFloat(val.stock_transaction_qty)) - (val.stock_transaction_price * parseFloat(val.stock_transaction_qty)) - parseFloat(val.Charges)) : ((parseFloat(value.price_detail_intraday.close) * val.stock_transaction_qty) - (val.stock_transaction_price * val.stock_transaction_qty) - parseFloat(val.Charges));

                    if (overview_overall_p_p_l > 0){
                        if (profit_fincode.indexOf(parseInt(value.stock_fincode)) == -1){
                            num_profit_overall += 1;
                            profit_fincode.push(parseInt(value.stock_fincode));
                        }

                        total_profit_overall += overview_overall_p_p_l;
                    } else{

                        if (loss_fincode.indexOf(parseInt(value.stock_fincode)) == -1){
                            num_loss_overall += 1;
                            loss_fincode.push(parseInt(value.stock_fincode));
                        }

                        total_loss_overall += overview_overall_p_p_l * parseFloat(val.stock_transaction_qty);
                    }
                } else if (tab == 'dashboard'){
                    if (parseInt(val.stock_transaction_date) in dates_obj) dates_obj[parseInt(val.stock_transaction_date)] += parseFloat(val.stock_transaction_price) * parseFloat(val.stock_transaction_qty) + parseFloat(val.Charges);
                    else dates_obj[parseInt(val.stock_transaction_date)] = (parseFloat(val.stock_transaction_price) * parseFloat(val.stock_transaction_qty)) + parseFloat(val.Charges);

                    if (parseInt(val.stock_transaction_date) in type_dates_obj){
                        if ('Stocks' in type_dates_obj[parseInt(val.stock_transaction_date)]) type_dates_obj[parseInt(val.stock_transaction_date)]['Stocks'].push(parseFloat(val.stock_transaction_price) * parseFloat(val.stock_transaction_qty) + parseFloat(val.Charges));
                        else type_dates_obj[parseInt(val.stock_transaction_date)]['Stocks'] = [parseFloat(val.Charges) + (parseFloat(val.stock_transaction_price) * parseFloat(val.stock_transaction_qty))];
                    } else {
                        type_dates_obj[parseInt(val.stock_transaction_date)] = {'Stocks': [parseFloat(val.Charges) + (parseFloat(val.stock_transaction_price) * parseFloat(val.stock_transaction_qty))]};
                    }
                }

                total_volume_of_stock += parseFloat(val.stock_transaction_qty);
                if (parseInt(val.stock_transaction_date) >= financial_yr_timestamp){
                    if (parseFloat(val.stock_transaction_qty) < 0) asset_sold_this_year += -1 * (parseFloat(val.stock_transaction_qty) * parseFloat(val.stock_transaction_price) + parseFloat(val.Charges));
                    else{
                        fincode_added_this_fyr[value.stock_fincode] = parseInt(val.stock_transaction_qty);
                        asset_added_this_year += parseFloat(val.Charges) + (parseFloat(val.stock_transaction_qty) * parseFloat(val.stock_transaction_price));
                    }
                };
            });

            if (value.price_detail_intraday == null) {

                if (value.stock_fincode in fincode_added_this_fyr) currentVal_of_asset_fyr += (parseFloat(value.price_detail_adjusted.close) * fincode_added_this_fyr[value.stock_fincode]);
                current_val_of_stock = (parseFloat(value.price_detail_adjusted.close) * total_volume_of_stock);
                adjusted_val_of_stock = (parseFloat(value.price_detail_adjusted.close) * total_volume_of_stock);
                currentVal       += current_val_of_stock;
                adjustedValTotal += adjusted_val_of_stock;

            } else {

                if (value.stock_fincode in fincode_added_this_fyr) currentVal_of_asset_fyr += (parseFloat(value.price_detail_intraday.close) * fincode_added_this_fyr[value.stock_fincode]);
                current_val_of_stock = (parseFloat(value.price_detail_intraday.close) * total_volume_of_stock);
                adjusted_val_of_stock = (parseFloat(value.price_detail_adjusted.close) * total_volume_of_stock);
                currentVal       += current_val_of_stock;
                adjustedValTotal += adjusted_val_of_stock;

                if (tab == 'overview' && content == 'stocks'){
                    overview_daily_p_p_l = parseFloat(value.price_detail_intraday.close) - parseFloat(value.price_detail_adjusted.close);
                    if (overview_daily_p_p_l > 0){
                        num_profit_days   += 1;
                        total_profit_days += (overview_daily_p_p_l * total_volume_of_stock);
                    } else{
                        num_loss_days   += 1;
                        total_loss_days += (overview_daily_p_p_l * total_volume_of_stock);
                    }
                }

            }

            if (tab == 'overview' && content == 'stocks'){
                overview_table_to_append = `<tr>`;
                if (days_held_of_stock.length > 1){
                   overview_table_to_append += `<th scope="row"><span style="margin: 0.75em;">`+ value.compname +`(`+ days_held_of_stock.length +`)</span></th>`;
                   hover_title_overview_stocks = '';
                   for (st = 0; st < days_held_of_stock.length-1; st++) hover_title_overview_stocks += days_held_of_stock[st] +', ';
                   hover_title_overview_stocks += days_held_of_stock[days_held_of_stock.length-1] +'.';
                   days_held_line = `<td style='cursor: default;' title="`+ hover_title_overview_stocks +`">Hover</td>`;
                }
                else{
                   overview_table_to_append += `<th scope="row"><span style="margin: 0.75em;">`+ value.compname +`</span></th>`;
                   days_held_line = `<td>`+ days_held_of_stock[0] +`</td>`;
                }

                fincode_stock_weightage_invested[value.compname] = parseInt(total_inv_val_of_stock * 100) / 100;
                fincode_stock_weightage_current[value.compname] = parseInt(current_val_of_stock * 100) / 100;
                if (value.ind_name in fincode_sector_weightage_invested) fincode_sector_weightage_invested[value.ind_name] += parseInt(total_inv_val_of_stock * 100) / 100;
                else fincode_sector_weightage_invested[value.ind_name] = parseInt(total_inv_val_of_stock * 100) / 100;
                if (value.ind_name in fincode_sector_weightage_current) fincode_sector_weightage_current[value.ind_name] += parseInt(current_val_of_stock * 100) / 100;
                else fincode_sector_weightage_current[value.ind_name] = parseInt(current_val_of_stock * 100) / 100;

                if (value.category in fincode_mcap_weightage_invested) fincode_mcap_weightage_invested[value.category] += parseInt(total_inv_val_of_stock * 100) / 100;
                else fincode_mcap_weightage_invested[value.category] = parseInt(total_inv_val_of_stock * 100) / 100;
                if (value.category in fincode_mcap_weightage_current) fincode_mcap_weightage_current[value.category] += parseInt(current_val_of_stock * 100) / 100;
                else fincode_mcap_weightage_current[value.category] = parseInt(current_val_of_stock * 100) / 100;
                cmp = (value.price_detail_intraday == null) ? value.price_detail_adjusted.close : value.price_detail_intraday.close;

                _todays_profit_     = (current_val_of_stock - adjusted_val_of_stock).toFixed(2)
                _todays_profit_per_ = (100 * _todays_profit_ / adjusted_val_of_stock).toFixed(2)

                _overall_profit_     = (current_val_of_stock - total_inv_val_of_stock).toFixed(2)
                _overall_profit_per_ = (100 * _overall_profit_ / total_inv_val_of_stock).toFixed(2)

                overview_table_to_append +=`<td>&#8377;`+ parseFloat(cmp).toFixed(2) +`</td>
                                            <td>`+ total_volume_of_stock +`<br><small>&#8377;`+ (total_inv_val_of_stock / total_volume_of_stock).toFixed(2) +`</small></td>`
                                            + days_held_line +
                                            `<td>&#8377;`+ total_inv_val_of_stock.toFixed(2) +`<br><small>`+ (100 * (total_inv_val_of_stock) / <?php echo $wo['portfolio_data']['stock_invested_value']; ?>).toFixed(2) +`%</small></td>
                                            <td>&#8377;`+ _todays_profit_ +`<br><small>`+ _todays_profit_per_ +`%</small></td>
                                            <td>&#8377;`+ _overall_profit_ +`<br><small>`+ _overall_profit_per_ +`%</small></td>
                                            <td>Add</td>
                                            <td>&#8377;`+ (current_val_of_stock - total_inv_val_of_stock).toFixed(2) +`</td>
                                            <td>&#8377;`+ current_val_of_stock.toFixed(2) +`<br><small><span id='`+ num_of_trs +`_weightage_stocks'>`+ (100 * current_val_of_stock).toFixed(2) +`</span>%</small></td>
                                            <td><a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Upgrade to view XIRR">Pro</a></td>`

                overview_table_to_append += `</tr>`;
                num_of_trs += 1;

                _todays_profit_per_ = parseFloat(_todays_profit_per_);
                _overall_profit_per_ = parseFloat(_overall_profit_per_);

                if (today_max_per < _todays_profit_per_){
                    today_max = _todays_profit_;
                    today_max_per = _todays_profit_per_;
                    today_max_comp = value.compname;
                }
                if (today_min_per > _todays_profit_per_){
                    today_min = _todays_profit_;
                    today_min_per = _todays_profit_per_;
                    today_min_comp = value.compname;
                }

                if (overall_max_per < _overall_profit_per_){
                    overall_max = _overall_profit_;
                    overall_max_per = _overall_profit_per_;
                    overall_max_comp = value.compname;
                }
                if (overall_min_per > _overall_profit_per_){
                    overall_min = _overall_profit_;
                    overall_min_per = _overall_profit_per_;
                    overall_min_comp = value.compname;
                }

                $('#overview_stocks_table_body').append(overview_table_to_append);
            }
        });

        currentVal_toDisplay = parseFloat($('#currentVal').text()) + currentVal;
        $('#currentVal').text(currentVal_toDisplay.toFixed(2));

        const daily_p_p_l = (currentVal - adjustedValTotal);
        $('#daily_p_p_l').text((parseFloat($('#daily_p_p_l').text()) + daily_p_p_l).toFixed(2));

        const overall_p_p_l = (currentVal - <?php echo $wo['portfolio_data']['stock_invested_value']; ?>);
        $('#overall_p_p_l').text((parseFloat($('#overall_p_p_l').text()) + overall_p_p_l).toFixed(2));

        if (tab == 'dashboard'){
            $('#total_assets').text(currentVal_toDisplay.toFixed(2));
            $('#total_current_value').text(currentVal_toDisplay.toFixed(2));
            $('#currentValTable').text(currentVal.toFixed(2));

            var invested_fyr_toDisplay = parseFloat($('#asset_added_this_year').text()) + asset_added_this_year;
            $('#asset_added_this_year').text(invested_fyr_toDisplay.toFixed(2));

            var p_l_this_year = currentVal_of_asset_fyr - asset_added_this_year;
            var p_l_fyr_toDisplay = parseFloat($('#p_l_this_year').text()) + p_l_this_year;
            $('#p_l_this_year').text(p_l_fyr_toDisplay.toFixed(2));
            $('#asset_sold_this_year').text(asset_sold_this_year);

            $('#daily_p_p_lTable').text(daily_p_p_l.toFixed(2));

            const daily_p_p_l_per = ((daily_p_p_l / adjustedValTotal) * 100);
            change_colors('daily_p_p_l', daily_p_p_l_per);
            change_colors('daily_p_p_lTable', daily_p_p_l_per);

            $('#overall_p_p_lTable').text(overall_p_p_l.toFixed(2));

            $('#total_day_gain').text((parseFloat($('#total_day_gain').text()) + daily_p_p_l).toFixed(2));
            $('#total_unrealised_gain').text((parseFloat($('#total_unrealised_gain').text()) + overall_p_p_l).toFixed(2));

            const overall_p_p_l_per = (overall_p_p_l / <?php echo $wo['portfolio_data']['stock_invested_value']; ?>) * 100;
            change_colors('overall_p_p_lTable', overall_p_p_l_per);
        }else if (tab == 'overview' && content == 'stocks'){

            for (var ind_name in fincode_sector_weightage_current){
                fincode_sector_weightage_profit[ind_name] = fincode_sector_weightage_current[ind_name] - fincode_sector_weightage_invested[ind_name];
                fincode_sector_weightage_profit_per[ind_name] = parseInt(((fincode_sector_weightage_profit[ind_name]) / fincode_sector_weightage_invested[ind_name]) * 10000) / 100;
            }

            add_weightage_Overview(fincode_stock_weightage_current,
                fincode_sector_weightage_current,
                fincode_stock_weightage_invested,
                fincode_sector_weightage_invested,
                fincode_sector_weightage_profit,
                fincode_sector_weightage_profit_per);

            add_marketCap_Overview(fincode_mcap_weightage_invested, fincode_mcap_weightage_current);
            $('#num_gain_day').text(num_profit_days);
            $('#num_loss_day').text(num_loss_days);
            $('#gain_overall').text(total_profit_overall.toFixed(2));
            $('#loss_overall').text(total_loss_overall.toFixed(2));
            $('#num_gain_overall').text(num_profit_overall);
            $('#num_loss_overall').text(num_loss_overall);
            $('#gain_day').text(total_profit_days.toFixed(2));
            $('#loss_day').text(total_loss_days.toFixed(2));
            if (today_max_per > 0){
                $('#top_gainer_day').text(today_max_comp);
                $('#top_gainer_day_amount').text(today_max);
                $('#top_gainer_day_per').text(today_max_per);
            }
            if (today_min_per < 0){
                $('#top_loser_day').text(today_min_comp);
                $('#top_loser_day_amount').text(today_min);
                $('#top_loser_day_per').text(today_min_per);
            }
            if (overall_max_per > 0){
                $('#top_profit_overall').text(overall_max_comp);
                $('#top_profit_overall_amount').text(overall_max);
                $('#top_profit_overall_per').text(overall_max_per);
            }
            if (overall_min_per < 0){
                $('#top_loss_overall').text(overall_min_comp);
                $('#top_loss_overall_amount').text(overall_min);
                $('#top_loss_overall_per').text(overall_min_per);
            }

            for (tr_num = 0; tr_num < num_of_trs; tr_num++) $('#' + tr_num + '_weightage_stocks').text((parseFloat($('#' + tr_num + '_weightage_stocks').text()) / currentVal).toFixed(2));
            const daily_p_p_l_per = ((daily_p_p_l / adjustedValTotal) * 100);
            const overall_p_p_l_per = (overall_p_p_l / <?php echo $wo['portfolio_data']['stock_invested_value']; ?>) * 100;

            last_tr = `<tr style="background-color:grey">
                           <th scope="row"><span style="margin: 0.75em; color: white;">Total</span></th>
                           <td><span style="color: white;">-</span></td>
                           <td><span style="color: white;">`+ <?php echo $wo['portfolio_data']['no_of_stocks']; ?> +`<br><small>&#8377;`+ (<?php echo $wo['portfolio_data']['stock_invested_value']; ?> / <?php echo $wo['portfolio_data']['no_of_stocks']; ?>).toFixed(2) +`</small></span></td>
                           <td><span style="color: white;">-</span></td>
                           <td><span style="color: white;">&#8377;<?php echo round($wo['portfolio_data']['stock_invested_value'], 2); ?></span></td>
                           <td><span style="color: white;">&#8377;`+ daily_p_p_l.toFixed(2) +`<br><small>`+ (daily_p_p_l_per).toFixed(2) +`%</small></span></td>
                           <td><span style="color: white;">&#8377;`+ overall_p_p_l.toFixed(2) +`<br><small>`+ (overall_p_p_l_per).toFixed(2) +`%</small></span></td>
                           <td><span style="color: white;">-</span></td>
                           <td><span style="color: white;">&#8377;`+ overall_p_p_l.toFixed(2) +`<br><small>`+ (overall_p_p_l_per).toFixed(2) +`%</small></span></td>
                           <td><span style="color: white;">&#8377;<span id='currentVal_stocks_Overview'>`+ currentVal +`</span></span></td>
                           <td><span style="color: white;"><a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>" style="color: white;">Pro</a></span></td>
                       </tr>`;

            $('#overview_stocks_table_body').append(last_tr);
            add_doughnutCharts_Overview(total_profit_overall, total_loss_overall, total_profit_days, total_loss_days);
        }

        return currentVal.toFixed(2);
    }

    function averageBuyingPrice({n, total}, stock_portfolio_data) {
        if (stock_portfolio_data.stock_transaction_qty < 0) {
            return {n, total};
        }
        return {
            n:   n + parseFloat(stock_portfolio_data.stock_transaction_qty),
            total: total + (parseFloat(stock_portfolio_data.stock_transaction_price) * parseFloat(stock_portfolio_data.stock_transaction_qty)) + parseFloat(stock_portfolio_data.Charges),
        };
    }

    function change_dynamic_colors(){
        if (parseFloat($('#overall_p_p_l_per').text()) > 0){
            /* $('#p_l_added_this_year_unrealised_div').removeClass('SA_border-left-secondary'); */
            /* $('#p_l_added_this_year_unrealised_text_ruppee').removeClass('SA_text-gray-800'); */
            $('#overall_p_p_l_div').addClass('SA_border-left-success');
            $('#overall_p_p_l_text').addClass('SA_text-success');
            /* $('#p_l_added_this_year_unrealised_text_ruppee').addClass('SA_text-success'); */
        } else if (parseFloat($('#overall_p_p_l_per').text()) < 0){
            /* $('#p_l_added_this_year_unrealised_text_ruppee').removeClass('SA_text-gray-800'); */
            $('#overall_p_p_l_div').addClass('SA_border-left-danger');
            $('#overall_p_p_l_text').addClass('SA_text-danger');
            /* $('#p_l_this_year').addClass('SA_text-danger'); */
            /* $('#p_l_added_this_year_unrealised_text_ruppee').addClass('SA_text-danger'); */
        }

        if (parseFloat($('#daily_p_p_l_per').text()) > 0){
            /* $('#p_l_added_this_year_unrealised_div').removeClass('SA_border-left-secondary'); */
            /* $('#p_l_added_this_year_unrealised_text_ruppee').removeClass('SA_text-gray-800'); */
            $('#daily_p_p_l_div').addClass('SA_border-left-success');
            $('#daily_p_p_l_text').addClass('SA_text-success');
            /* $('#p_l_added_this_year_unrealised_text_ruppee').addClass('SA_text-success'); */
        } else if (parseFloat($('#daily_p_p_l_per').text()) < 0){
            /* $('#p_l_added_this_year_unrealised_text_ruppee').removeClass('SA_text-gray-800'); */
            $('#daily_p_p_l_div').addClass('SA_border-left-danger');
            $('#daily_p_p_l_text').addClass('SA_text-danger');
            /* $('#p_l_this_year').addClass('SA_text-danger'); */
            /* $('#p_l_added_this_year_unrealised_text_ruppee').addClass('SA_text-danger'); */
        }

        if (parseFloat($('#p_l_this_year').text()) > 0){
            /* $('#p_l_added_this_year_unrealised_div').removeClass('SA_border-left-secondary'); */
            /* $('#p_l_added_this_year_unrealised_text_ruppee').removeClass('SA_text-gray-800'); */
            $('#p_l_added_this_year_unrealised_div').addClass('SA_border-left-success');
            $('#p_l_added_this_year_unrealised_text').addClass('SA_text-success');
            /* $('#p_l_added_this_year_unrealised_text_ruppee').addClass('SA_text-success'); */
        } else if (parseFloat($('#p_l_this_year').text()) < 0){
            /* $('#p_l_added_this_year_unrealised_text_ruppee').removeClass('SA_text-gray-800'); */
            $('#p_l_added_this_year_unrealised_div').addClass('SA_border-left-danger');
            $('#p_l_added_this_year_unrealised_text').addClass('SA_text-danger');
            /* $('#p_l_this_year').addClass('SA_text-danger'); */
            /* $('#p_l_added_this_year_unrealised_text_ruppee').addClass('SA_text-danger'); */
        }
    }

    function change_colors(tag, p_l_per){
       $('#'+ tag +'_per').text(p_l_per.toFixed(2));
       if (p_l_per > 0){
           $('#'+ tag +'_div').removeClass('SA_border-left-danger');
           $('#'+ tag +'_div').removeClass('SA_border-left-secondary');
           $('#'+ tag +'_text').removeClass('SA_text-danger');
           $('#'+ tag +'_text').removeClass('SA_text-secondary');

           $('#'+ tag +'_text').addClass('SA_text-success');
           $('#'+ tag +'_div').addClass('SA_border-left-success');
       } else if(p_l_per == 0) {
           $('#'+ tag +'_div').removeClass('SA_border-left-success');
           $('#'+ tag +'_div').removeClass('SA_border-left-danger');
           $('#'+ tag +'_text').removeClass('SA_text-danger');
           $('#'+ tag +'_text').removeClass('SA_text-success');

           $('#'+ tag +'_text').addClass('SA_text-secondary');
           $('#'+ tag +'_div').addClass('SA_border-left-secondary');
           $('#'+ tag +'_progress').addClass('SA_bg-secondary');
       } else {
           $('#'+ tag +'_div').removeClass('SA_border-left-success');
           $('#'+ tag +'_div').removeClass('SA_border-left-secondary');
           $('#'+ tag +'_text').removeClass('SA_text-success');
           $('#'+ tag +'_text').removeClass('SA_text-secondary');

           $('#'+ tag +'_text').addClass('SA_text-danger');
           $('#'+ tag +'_div').addClass('SA_border-left-danger');
       }
    }


    function change_upper_values(data){

       const initialVals       = {n: 0, total: 0};
       const stock_portfolio_data_average_length = data.stock_portfolio_data.reduce(averageBuyingPrice, initialVals);
       console.log(stock_portfolio_data_average_length);

       const volume_in_portfolio = stock_portfolio_data_average_length.n;
       $('#volume_in_portfolio').text(volume_in_portfolio);

       const total_buying_price = stock_portfolio_data_average_length.total;
       $('#total_buying_price').text(total_buying_price);

       const average_buying_price = total_buying_price/volume_in_portfolio;
       $('#average_buying_price').text(average_buying_price);

       if (data.price_detail_intraday != null){

           $('#current_stock_value').text(data.price_detail_intraday.close);

           const daily_p_l = (data.price_detail_intraday.close - data.extra_stock_data.price_detail_adjusted.close) * volume_in_portfolio;
           $('#daily_p_l').text(daily_p_l);

           const daily_p_l_per = ((data.price_detail_intraday.close - data.extra_stock_data.price_detail_adjusted.close) / data.extra_stock_data.price_detail_adjusted.close) * 100;
           change_colors('daily_p_l', daily_p_l_per);

           const overall_p_l = (data.price_detail_intraday.close * volume_in_portfolio) - total_buying_price;
           $('#overall_p_l').text(overall_p_l);

           const overall_p_l_per = (overall_p_l / (data.price_detail_intraday.close * volume_in_portfolio)) * 100;
           change_colors('overall_p_l', overall_p_l_per);

       } else{

           $('#current_stock_value').text(data.price_detail_adjusted.close);

           const daily_p_l = 0;
           $('#daily_p_l').text(daily_p_l);

           const daily_p_l_per = 0;

           change_colors('daily_p_l', daily_p_l_per);

           const overall_p_l = (data.price_detail_adjusted.close * volume_in_portfolio) - total_buying_price;
           $('#overall_p_l').text(overall_p_l);

           const overall_p_l_per = (overall_p_l / (data.price_detail_adjusted.close * volume_in_portfolio)) * 100;

           change_colors('overall_p_l', overall_p_l_per);

       }
    }

</script>
