<div class="page_list row boosted_pages">
	<div class="col-xs-8 col-md-10" style="padding-bottom:5px">
	<script>console.log("<?php echo $wo['portfolio']['url'];?>")</script>
		<a href="<?php echo $wo['portfolio']['url'];?>" data-ajax="<?php echo  $wo['portfolio']['raw_url'];?>">
			<span class="page_title"><?php echo $wo['portfolio']['portfolio_name']; ?></span>
		</a>
		<div class="page_info">
			<ul>
				<li>
					<?php echo $wo['portfolio']['portfolio_description']; ?>
				</li>
				<li>
				<div style="color: #4d91ea;">
					<small>

						<?php if (!empty($wo['portfolio']['no_of_stocks'])):?>

						<span>No of unique stocks : <?php echo $wo['portfolio']['no_of_unique_stocks']; ?></span>
						<span>Daily Rank: <?php echo $wo['portfolio']['daily_rank']; ?></span>
						<span>Date Created: <?php echo $wo['portfolio']['timestamp_created']; ?></span>
						<span>Portfolio Age: 0</span>
						<span>Privacy: <?php echo ($wo['portfolio']['privacy_level'] < 3) ? "Public TODO all" : "Private"; ?></span>
						<span>Invested Amount: <?php echo $wo['portfolio']['total_invested_value']; ?></span>

						<?php else:?>
						<span>No Stocks in your portfolio, kindly <a href="<?php echo $wo['portfolio']['url'];?>" data-ajax="<?php echo  $wo['portfolio']['raw_url'];?>">add stocks</a>: </span>
						<?php endif; ?>

                        <span><a href="">Share</a></span>

					</small>
				</div>
				</li>
			</ul>
		</div>
	</div>
</div>
