<ul class="list-group filterby portfolio_graph_filter" id="filter-button" style="float: right;margin: 0;background-color: #f9f9f9; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.0);">

    <li class="list-group-item hidden" contenteditable="false">Graph by</li>

    <li class="list-group-item filter-by-li" id="TenD" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); color: #000;  border-radius: 5px; width: 20.4%;">
        <b>10D</b>
    </li>

    <li class="list-group-item filter-by-li" id="OneM" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); color: #000;  border-radius: 5px; width: 18.5%">
        <b>1M</b>
    </li>

    <li class="list-group-item filter-by-li" id="OneYr" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); color: #000;  border-radius: 5px; width: 18%">
        <b>1Yr</b>
    </li>

    <li class="list-group-item filter-by-li" id="YTD" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); color: #000;  border-radius: 5px; width: 20.6%">
        <b>YTD</b>
    </li>

    <li class="list-group-item filter-by-li avtive" id="MAX" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); color: #000;  border-radius: 5px; width: 22.5%">
        <b>MAX</b>
    </li>

</ul>
