<li>

    <a href="javascript:void(0);" onclick="AddStockToTable(<?php echo $wo['result']['fincode']; ?>, '<?php echo $wo['result']['compname']; ?>')">
        <span class="page_title"><?php echo $wo['result']['compname']; ?></span>
        <div style="color: #4d91ea;">
            <small>
                <?php if (!empty($wo['result']['scripcode'])):?>
                <span>BSE: <?php echo $wo['result']['scripcode']; ?></span>
                <?php endif; ?>
                <?php if (!empty($wo['result']['symbol'])):?>
                <span>NSE: <?php echo $wo['result']['symbol']; ?></span>
                <?php endif; ?>
                <?php if (!empty($wo['result']['ind_name'])):?>
                <span>Sector: <?php echo $wo['result']['ind_name']; ?></span>
                <?php endif; ?>
            </small>
        </div>
    </a>

	<div class="clear"></div>

</li>
