<div class="page-margin">
    <div class="col-md-12">
        <div class="page-margin wow_content">
            <div class="wo_page_hdng pag_neg_padd pag_alone">
                <div class="wo_page_hdng_menu">
                    <ul class="list-unstyled">
                        <li id='equity'><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=equity" data-ajax="<?php echo  $wo['portfolio_data']['raw_url'];?>&amp;tab=equity">Equity</a></li>
                        <li id='mutual_funds'><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=mutual_funds" data-ajax="<?php echo  $wo['portfolio_data']['raw_url'];?>&amp;tab=mutual_funds">Mutual Funds</a></li>
                        <li id='other_assets'><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=other_assets" data-ajax="<?php echo  $wo['portfolio_data']['raw_url'];?>&amp;tab=other_assets">Other Assets</a></li>
                        <li id='all_transactions'><a href="<?php echo $wo['portfolio_data']['url'];?>&amp;tab=transactions" data-ajax="<?php echo  $wo['portfolio_data']['raw_url'];?>&amp;tab=transactions">All Transactions</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="wo_my_pages">
            <div>

                <?php
                    $stocks_in_portfolios = Wo_GetDataOfStocksInPortfolio($wo['portfolio_data']['portfolio_id']);
                    if (count($stocks_in_portfolios) > 0) {
                        foreach ($stocks_in_portfolios as $wo['stock_in_portfolios']) {
                            echo Wo_LoadPage('portfolio/stocks_in_portfolio_list');
                        }
                    } else {
                        echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" viewBox="-50 0 600 500"><path fill="currentColor" d="M396.8 352h22.4c6.4 0 12.8-6.4 12.8-12.8V108.8c0-6.4-6.4-12.8-12.8-12.8h-22.4c-6.4 0-12.8 6.4-12.8 12.8v230.4c0 6.4 6.4 12.8 12.8 12.8zm-192 0h22.4c6.4 0 12.8-6.4 12.8-12.8V140.8c0-6.4-6.4-12.8-12.8-12.8h-22.4c-6.4 0-12.8 6.4-12.8 12.8v198.4c0 6.4 6.4 12.8 12.8 12.8zm96 0h22.4c6.4 0 12.8-6.4 12.8-12.8V204.8c0-6.4-6.4-12.8-12.8-12.8h-22.4c-6.4 0-12.8 6.4-12.8 12.8v134.4c0 6.4 6.4 12.8 12.8 12.8zM496 400H48V80c0-8.84-7.16-16-16-16H16C7.16 64 0 71.16 0 80v336c0 17.67 14.33 32 32 32h464c8.84 0 16-7.16 16-16v-16c0-8.84-7.16-16-16-16zm-387.2-48h22.4c6.4 0 12.8-6.4 12.8-12.8v-70.4c0-6.4-6.4-12.8-12.8-12.8h-22.4c-6.4 0-12.8 6.4-12.8 12.8v70.4c0 6.4 6.4 12.8 12.8 12.8z"/></svg>No portfolios to show</div>';
                    }
                ?>
            <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<script>

    $( document ).ready(function() {
        tab = '<?php echo $_GET['tab']; ?>';
        tab = tab === 'transactions' ? 'all_transactions' : tab;
        $('#' + tab).addClass('active');
        $('#transactions').addClass('menuactive');
        console.log('Tab: ' + tab);
    });

</script>
