<script>console.log(<?php echo json_encode($wo['stock_in_portfolios']); ?>)</script>
<div class="page_list row">
	<div class="col-xs-8 col-md-10" style="padding-bottom:5px">
        <a href="<?php echo $wo['portfolio_data']['url'];?>&amp;stock=<?php echo $wo['stock_in_portfolios']['fincode'];?>" data-ajax="<?php echo  $wo['portfolio_data']['raw_url'];?>&amp;stock=<?php echo $wo['stock_in_portfolios']['fincode'];?>" id="stock_in_portfolio" class="menuactive">
			<span class="page_title"><?php echo $wo['stock_in_portfolios']['compname']; ?></span>
		</a>
		<div class="page_info">
			<ul>
				<li>
					View <?php echo $wo['stock_in_portfolios']['s_name']; ?>'s Live Quote, Qtrly Results, Fin Ratios, Bal Sheet, P&L and much more...
				</li>
				<li>
				<div style="color: #4d91ea;">
					<small>
						<?php if (!empty($wo['stock_in_portfolios']['scripcode'])):?>
						<span>BSE: <?php echo $wo['stock_in_portfolios']['scripcode']; ?></span>
						<?php endif; ?>
						<?php if (!empty($wo['stock_in_portfolios']['symbol'])):?>
						<span>NSE: <?php echo $wo['stock_in_portfolios']['symbol']; ?></span>
						<?php endif; ?>
						<?php if (!empty($wo['stock_in_portfolios']['ind_name'])):?>
						<span>Sector: <?php echo $wo['stock_in_portfolios']['ind_name']; ?></span>
						<?php endif; ?>
					</small>
				</div>
				</li>
			</ul>
		</div>
	</div>
</div>
