<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var StockSearchContainer = $('.stock-search-container');
    var StockSearchResult = $('.stock-search-dropdown-result');
    var stock_quotes_to_add = {};
    var stock_num = 0;

    function Wo_StockSearchResult(query) {
        if (query != '') {
            Wo_progressIconLoader(StockSearchContainer.find('.stock_search'));
            StockSearchContainer.addClass('open');
            $.get(Wo_Ajax_Requests_File(), {f: 'search', s: 'stock_quote', query: query}, function(data) {
                if (data.status == 200) {
                    if (data.html.length == 0) {
                        StockSearchResult.html('<span class="center-text">' + " <?php echo $wo['lang']['no_result']; ?>" + '<span>');
                    } else {
                        StockSearchResult.html(data.html);
                    }
                }
                Wo_progressIconLoader(StockSearchContainer.find('#stock_search'));
            });
            $(document).click(function() {
                StockSearchContainer.removeClass('open');
            });
        } else {
            StockSearchContainer.removeClass('open');
        }
    }

    function AddStockToTable(fincode, comp_name){
        if (!stock_quotes_to_add.length){
            $('#stock_container').addClass('hidden');
            $('#stock_quote_table_search').removeClass('hidden');
        }
        table_body_data_to_add = `<tr id=`+ fincode + stock_num +` style="height:39px">
                                     <td id="stock_name" class="stock_quote_name_search">` + comp_name + `</td>
                                     <td><input id="stock_transaction_date" type="date" name="transaction_date"/></td>
                                     <td>
                                         <span class="stock_quote_transac_price_div">
                                             <input id="stock_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" onkeyup=changeValues(`+ fincode + stock_num +`) onchange=changeValues(`+ fincode + stock_num +`) />
                                         </span>
                                     </td>
                                      <td><input id="stock_qty" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="quantity" style="height:39px;" onkeyup=changeValues(`+ fincode + stock_num +`) onchange=changeValues(`+ fincode + stock_num +`) /></td>
                                     <td><select name='exchange' id='exchange' style="width: 6em; height: 2.75em;"><option value="BSE">BSE</option><option value="NSE">NSE</option></select></td>
                                     <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteStockQuoteFromSearch('`+ fincode + stock_num +`')"></i></td>
                                   </tr>
                                   <tr id=`+ fincode + stock_num +`charge style="height:39px">
                                     <td>Amount: <span id=`+ fincode + stock_num +`amount_>0</span></td>
                                     <td id='all_charges' title="Current Charges: 0">Charge: <span id=`+ fincode + stock_num +`charge_>0</span></td>
                                     <td><input style="text-decoration: none; cursor: default;" id="brokerage" type="number" value=0 step="any" onkeyup=changeValues(`+ fincode + stock_num +`) onchange=changeValues(`+ fincode + stock_num +`) /><select name='percentage_inr' id='percentage_inr' onchange=changeValues(`+ fincode + stock_num +`) ><option value="Percentage">Percentage</option><option value="INR">INR</option></select></td>
                                     <td colspan="2">Brokerage Charge: <span id=`+ fincode + stock_num +`broker_charge_>0</span></td>
                                     <td>Net Amount: <span id=`+ fincode + stock_num +`net_amount>0</span></td>
                                  </tr>
                                  <tr id=`+ fincode + stock_num +`stock_notes style="height:39px">
                                     <td colspan="7"> <span class="small">Notes:</span> <br> <span> <textarea name="notes" id="notes" rows="1"></textarea> </span> </textarea></td>
                                  </tr>`;


        stock_quotes_to_add[stock_num] = fincode;
        stock_num += 1;

        $('#table_stock_quote_search_body').append(table_body_data_to_add);
    }

    function changeValues(id){
        amount = $("#"+id + " #stock_qty").val() * $("#"+id + " #stock_transaction_price").val();
        stt_charge = amount * 0.001;
        exchange_charge = ($("#"+id + " #exchange").val()=="BSE") ? (amount * 0.0000275) : (amount * 0.0000325);
        sebi_charge = amount * 0.000001;
        stamp_duty = amount * 0.00000;
        brokerage_charge = ($("#"+id + "charge #percentage_inr").val()=="INR") ? parseFloat($("#"+id + "charge #brokerage").val()) : (amount * $("#"+id + "charge #brokerage").val()/100);
        charge = stt_charge + exchange_charge + sebi_charge + stamp_duty;
        net_amount = amount + charge + brokerage_charge;
        $("#"+id+"broker_charge_").text(brokerage_charge.toFixed(2));
        $("#"+id+"charge_").text(charge.toFixed(2));
        $("#"+id+"charge #all_charges").attr('title', ' STT Charge: '+stt_charge.toFixed(2)+'\n Exchange Charge: '+exchange_charge.toFixed(2)+'\n Sebi Charge: '+sebi_charge.toFixed(2)+'\n Stamp Duty: '+stamp_duty.toFixed(2));
        $("#"+id+"amount_").text(amount.toFixed(2));
        $("#"+id+"net_amount").text(net_amount.toFixed(2));
    }

    function deleteStockQuoteFromSearch(id){

        delete stock_quotes_to_add[id.slice(6)];

        if (!(Object.keys(stock_quotes_to_add).length)){
            $('#stock_container').removeClass('hidden');
            $('#stock_quote_table_search').addClass('hidden');
        }

        $("#"+id).remove();
        $("#"+id+"charge").remove();
        $("#"+id+"stock_notes").remove();
    }

    function ajax_call_for_stocks(stocks_array_to_send, auto_add_, no_of_stocks){
        console.log(auto_add_);
        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'portfolio_data',
                stock_array: stocks_array_to_send,
                no_of_stocks: no_of_stocks,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                auto_add: auto_add_,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        Swal.fire({
                            icon: 'success',
                            title: 'Stocks Added Successfully!',
                        }).then((result) => {
                            localStorage.removeItem(<?php echo $wo['portfolio_data']['portfolio_id']; ?> + "_portfolio_assets");
                            location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>';
                        })
                    }
                    else if (data['status'] == 401){
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                    }
                    else{
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                        console.log(data['error']);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

    function pushStockDataToBackend(){
        var stocks_array_to_send = new Array();
        var stocks_total_price = 0;
        var no_of_stocks = 0;
        var earliest_stocks_date = undefined;

        Object.keys(stock_quotes_to_add).forEach(function (id){
            if ($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val() === ""){
                /* alert('Please Enter a Date'); */
                /* $("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val(new Date().toDateInputValue()); */
                $("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val("NaN");
            }
            /* console.log($("#"+stock_quotes_to_add[id]+id+"charge_").text()) */

            stocks_total_price += parseFloat($("#"+stock_quotes_to_add[id]+id+"net_amount").text());
            if((earliest_stocks_date == undefined) || (parseInt(new Date($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val()).getTime()/1000))) earliest_stocks_date = parseInt(new Date($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val()).getTime()/1000);

            stockInfo = {

                    stock_fincode: parseInt(stock_quotes_to_add[id]),
                    stock_transaction_date: parseInt(new Date($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val()).getTime()/1000),
                    stock_transaction_price: parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_price").val()),
                    stock_transaction_qty: parseInt($("#"+stock_quotes_to_add[id]+id+" #stock_qty").val()),
                    stock_invested_value: parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_qty").val()) * parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_price").val()),
                    stock_charge: parseFloat($("#"+stock_quotes_to_add[id]+id+"charge_").text()) + parseFloat($("#"+stock_quotes_to_add[id]+id+"broker_charge_").text()),
                    note: $("#"+stock_quotes_to_add[id]+id+"stock_notes #notes").val(),
                    stock_net_amount: parseFloat($("#"+stock_quotes_to_add[id]+id+"net_amount").text()),

                        };

            no_of_stocks += parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_qty").val());
            stocks_array_to_send.push(stockInfo);
        });

        console.log(stocks_array_to_send);

        /* no_of_unique_stocks = [...new Set(Object.values(stock_quotes_to_add))].length; */
        /* console.log("no_of_unique_stocks"); */
        /* console.log(no_of_unique_stocks); */

        console.log(stocks_total_price);
        console.log(<?php echo $wo['portfolio_data']['current_value_cash']; ?>);
        if (stocks_total_price > <?php echo $wo['portfolio_data']['current_value_cash']; ?>){
            Swal.fire({
                title: '<p style="color: red;">Insufficient Cash Available</p>',
                text: 'Cash Available: ₹<?php echo $wo['portfolio_data']['current_value_cash']; ?> & Transaction Cost: ₹' + stocks_total_price,
                width: 400,
                padding: '3em',
                showCancelButton: false,
                showCloseButton: true,
                showDenyButton: true,
                confirmButtonColor: 'green',
                denyButtonColor: '#236CB0',
                denyButtonText: 'Add Cash Automatically',
                confirmButtonText: 'Add Cash Manually',
                showLoaderOnConfirm: true,
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Add Cash Manually',
                        text: 'Minimum Amount To Add For This Transaction: ₹' + (stocks_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>).toFixed(2),
                        input: 'number',
                        inputAttributes: { min: (stocks_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>).toFixed(2), step: 0.01 },
                        validationMessage: 'Added amount is less than Required amount!',
                        showCloseButton: true,
                        showCancelButton: true,
                        confirmButtonText: 'Add',
                        preConfirm: (amount) => {
                            $.ajax({
                                url: Wo_Ajax_Requests_File(),
                                type: 'GET',
                                dataType: 'json',
                                data: {
                                    f:'add_cash_for_asset',
                                    cash: amount,
                                    portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                                    note: 'Manually added cash for buying Stocks',
                                    date_: earliest_stocks_date,
                                }
                            });
                        },
                        allowOutsideClick: () => !Swal.isLoading()
                    }).then((result) => {
                        if (result.isConfirmed) {
                            ajax_call_for_stocks(stocks_array_to_send, '0', no_of_stocks);
                        }
                    })
                } else if (result.isDenied) {
                    ajax_call_for_stocks(stocks_array_to_send, '1', no_of_stocks);
                }
            })
        } else {
            ajax_call_for_stocks(stocks_array_to_send, '0', no_of_stocks);
        }
    }

</script>
