<table style="text-align: right; margin-bottom: 0em;" class="table table-bordered table-striped">

    <thead class="SA_card-header SA_py-3">
        <tr>
            <th style="vertical-align: top;" class="SA_text-primary"><span style="margin: 0.75em;">Asset Name</span></th>
            <th style="text-align: right;" class="SA_text-primary">Invested Amount <br><small>Date</small></th>
            <th style="text-align: right;" class="SA_text-primary">Latest Value<br><small>Update Date</small></th>
            <th style="text-align: right;" class="SA_text-primary">Unrealised Gain<br><small>Change%</small></th>
        </tr>
    </thead>

    <tbody id="overview_mf_table_body"></tbody>

</table>
