<table style="text-align: right; margin-bottom: 0em;" class="table table-bordered table-striped" id="fd_overview_table">
    <thead class="SA_card-header SA_py-3">
        <tr>
            <th style="vertical-align: top;" class="SA_text-primary"><span style="margin: 0.75em;">FD Type</span></th>
            <th style="vertical-align: top;" class="SA_text-primary"><span style="margin: 0.75em;">Bank Name</span></th>
            <th style="text-align: right;" class="SA_text-primary">Interest<br><small>Frequency</small></th>
            <th style="vertical-align: top; text-align: right;" class="SA_text-primary">Period</th>
            <th style="text-align: right;" class="SA_text-primary">Invested Amount<br><small>Start Date</small></th>
            <th style="text-align: right;" class="SA_text-primary">Maturity Amount<br><small>Date</small></th>
            <th style="vertical-align: top; text-align: right;" class="SA_text-primary">Current Value</th>
            <th style="vertical-align: top; text-align: right;" class="SA_text-primary">Interest Paid Out</th>
        </tr>
    </thead>

    <tbody id="overview_mf_table_body"></tbody>

</table>
