<div id="SA_content">

    <div class="SA_container-fluid">

        <div class="SA_row">

            <div class="SA_col-xl-6 SA_col-lg-6">

                <div class="SA_row" style="margin-bottom: 0em !important;margin-top: 1.4em;">

                    <div class="SA_col-md-6 SA_mb-4" style="margin-bottom: 0em !important;">
                       <div class="SA_card SA_shadow SA_mb-4">

                            <!-- Card Body -->
                            <div class="SA_card-body" style="margin-bottom: 0em !important;padding: 0em !important;">
                                <div class="SA_row">
                                    <div class="SA_col-6" style="padding: 0em">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Today's Top Gainer</div>
                                            <br>
                                            <span style="font-size:120%; font-weight:500; color: green;"><span id="top_gainer_day">-</span></span>
                                            <br>
                                            <span style="font-size:110%;font-weight:500;" class="SA_text-success">&#8377;<span id="top_gainer_day_amount">0</span>&nbsp;<span style="font-size: 85%;">(<span id="top_gainer_day_per">0</span>%)</span></span>
                                        </div>
                                    </div>
                                    <div class="SA_col-6">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Today's Top Loser</div>
                                            <br>
                                            <span style="font-size:120%; font-weight:500; color: red;"><span id="top_loser_day">-</span></span>
                                            <br>
                                            <span style="font-size:110%;font-weight:500;" class="SA_text-danger">&#8377;<span id="top_loser_day_amount">0</span>&nbsp;<span style="font-size: 85%;">(<span id="top_loser_day_per">0</span>%)</span></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="SA_col-md-6 SA_mb-4" style="margin-bottom: 0em !important;">
                       <div class="SA_card SA_shadow SA_mb-4">

                            <!-- Card Body -->
                            <div class="SA_card-body" style="margin-bottom: 0em !important;padding-top: 0em !important;padding-left: 0em !important;padding-bottom: 0em !important;">
                                <div class="SA_row">
                                    <div class="SA_col-6">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Top Profit</div>
                                            <br>
                                            <span style="font-size:120%; font-weight:500;" class="SA_text-success"><span id="top_profit_overall">-</span></span>
                                            <br>
                                            <span style="font-size:115%;font-weight:500; color: green;">&#8377;<span id="top_profit_overall_amount">0</span>&nbsp;<span style="font-size: 85%">(<span id="top_profit_overall_per">0</span>%)</span></span>
                                        </div>
                                    </div>
                                    <div class="SA_col-6">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Top Loss</div>
                                            <br>
                                            <span style="font-size:120%; font-weight:500; color: red;"><span id="top_loss_overall">-</span></span>
                                            <br>
                                            <span style="font-size:115%;font-weight:500;" class="SA_text-danger">&#8377;<span id="top_loss_overall_amount">0</span>&nbsp;<span style="font-size: 85%;">(<span id="top_loss_overall_per">0</span>%)</span></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

                <!-- TODO REALIZED -->


            </div>

            <div class="SA_col-xl-6 SA_col-lg-6">
                <div class="SA_row" style="margin-bottom: 0em !important;margin-top: 1.4em;">

                    <div class="SA_col-md-6">
                       <div class="SA_card SA_shadow">

                            <!-- Card Body -->
                            <div class="SA_card-body" style="padding: 0em !important;">
                                <div class="SA_row">
                                    <div class="SA_col-6" style="padding: 0em">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Total Realised Gains</div>
                                            <br>
                                            <span style="font-size:150%;font-weight:500;" id="total_realised_gain_div">&#8377;<span id="total_mutual_funds_realised_gain">0</span></span>
                                        </div>
                                    </div>
                                    <div class="SA_col-6">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Total Dividend</div>
                                            <br>
                                            <span style="font-size:150%;font-weight:750;">&#8377;<span id="total_mutual_funds_dividend_amount">0</span></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="SA_col-md-6">
                       <div class="SA_card SA_shadow">

                            <!-- Card Body -->
                            <div class="SA_card-body" style="padding: 0em !important;">
                                <div class="SA_row">
                                    <div class="SA_col-6" style="padding: 0em">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Total Realised Gains</div>
                                            <br>
                                            <span style="font-size:150%;font-weight:500;" id="total_realised_gain_div">&#8377;<span id="total_mutual_funds_realised_gain">0</span></span>
                                        </div>
                                    </div>
                                    <div class="SA_col-6">
                                        <div style="margin-top:0.7em; margin-left: 2.1em; margin-bottom:1.1em;">
                                            <div style="margin-bottom: -1em; font-size:133%;font-weight:650; color: black;">Total Dividend</div>
                                            <br>
                                            <span style="font-size:150%;font-weight:750;">&#8377;<span id="total_mutual_funds_dividend_amount">0</span></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

    <div class="SA_row">
         <!-- Content Column -->
        <div class="SA_col-12 SA_mb-4">
             <!-- Extra Financial Data -->
             <div class="SA_card SA_shadow SA_mb-4" style="margin-bottom: 0em !important">
                <?php echo Wo_LoadPage('portfolio/overviewContents/overview_table_property'); ?>
             </div>
        </div>
    </div>

</div>

<script>

    function change_overview_weightage(val){
        console.log(val);
        switch(val){
            case 'stock_current':
                $('#stock_weightage_invested').addClass('hidden');
                $('#overview_stock_weightage_invested').addClass('hidden');
                $('#stock_weightage_current').removeClass('hidden');
                $('#overview_stock_weightage_current').removeClass('hidden');
                break;
            case 'stock_invested':
                $('#stock_weightage_current').addClass('hidden');
                $('#overview_stock_weightage_current').addClass('hidden');
                $('#stock_weightage_invested').removeClass('hidden');
                $('#overview_stock_weightage_invested').removeClass('hidden');
                break;
            case 'sector_current':
                $('#sector_weightage_current').removeClass('hidden');
                $('#overview_sector_weightage_current').removeClass('hidden');
                $('#sector_weightage_invested').addClass('hidden');
                $('#sector_weightage_profit_per').addClass('hidden');
                $('#overview_sector_weightage_invested').addClass('hidden');
                $('#overview_sector_weightage_profit_per').addClass('hidden');
                break;
            case 'sector_invested':
                $('#overview_sector_weightage_invested').removeClass('hidden');
                $('#sector_weightage_invested').removeClass('hidden');
                $('#sector_weightage_current').addClass('hidden');
                $('#sector_weightage_profit_per').addClass('hidden');
                $('#overview_sector_weightage_current').addClass('hidden');
                $('#overview_sector_weightage_profit_per').addClass('hidden');
                break;
            case 'sector_profit_per':
                $('#sector_weightage_profit_per').removeClass('hidden');
                $('#overview_sector_weightage_profit_per').removeClass('hidden');
                $('#sector_weightage_invested').addClass('hidden');
                $('#sector_weightage_current').addClass('hidden');
                $('#overview_sector_weightage_invested').addClass('hidden');
                $('#overview_sector_weightage_current').addClass('hidden');
                break;
            case 'mcap_current':
                $('#mcap_weightage_invested').addClass('hidden');
                $('#mcap_weightage_current').removeClass('hidden');
                $('#overview_mcap_weightage_invested').addClass('hidden');
                $('#overview_mcap_weightage_current').removeClass('hidden');
                break;
            case 'mcap_invested':
                $('#mcap_weightage_current').addClass('hidden');
                $('#mcap_weightage_invested').removeClass('hidden');
                $('#overview_mcap_weightage_current').addClass('hidden');
                $('#overview_mcap_weightage_invested').removeClass('hidden');
                break;
            default:
                console.log('Some Issue here');
                break;
        }

    }

    $( document ).ready(function() {
        content = '<?php echo (empty($_GET['content'])) ? 'stocks' : $_GET['content']; ?>';
        $('#' + content).addClass('active');
        console.log('Tab: ' + content);
    });

</script>
