<script>

    function current_value_allocation(ctx, currentVal_array){
        console.log(currentVal_array);
        var options = {
              series: currentVal_array,
              chart: {
              width: '100%',
              type: 'donut',
            },
            labels: ["Bullion", "Cash", "Fixed Deposit", "Other Assets", "Properties", "Stocks", "Mutual Funds"],
            tooltip: {enabled: false},
            plotOptions: {
              pie: {
                donut: {
                    labels: {
                        show: true,
                        value: {
                            formatter: function(val){return ('₹' + val);}
                        }
                    }
                },
              }
            },
            colors: ['#00876c', '#58a066', '#98b561', '#dac767', '#e09d4b', '#e06f45', '#d43d51'],
            dataLabels: {
              formatter(val, opts) {
                return (val.toFixed(1) + '%');
              }
            },
            animation: {
                enabled: false,
                dynamicAnimation: {
                    enabled: false,
                }
            },
            legend: {
              show: true,
              position: 'bottom'
            }
        };

        var chart = new ApexCharts(ctx, options);
        chart.render();

    };

</script>
