<script>

    function current_value_allocation(ctx, currentVal_array){
        console.log(currentVal_array);
        var options = {
              series: currentVal_array,
              chart: {
              width: '100%',
              type: 'donut',
            },
            labels: ["Bullion", "Cash", "Fixed Deposit", "Other Assets", "Properties", "Stocks", "Mutual Funds"],
            plotOptions: {
              pie: {
                dataLabels: {
                  offset: -5
                }
              }
            },
            colors: ['#00876c', '#58a066', '#98b561', '#dac767', '#e09d4b', '#e06f45', '#d43d51'],
            dataLabels: {
              formatter(val, opts) {
                const name = opts.w.globals.labels[opts.seriesIndex]
                return [name, val.toFixed(1) + '%']
              }
            },
            animation: {
                enabled: false,
                dynamicAnimation: {
                    enabled: false,
                }
            },
            legend: {
              show: false
            }
            };

        var chart = new ApexCharts(ctx, options);
        chart.render();

    };

</script>
