<script>

    function current_value_allocation(ctx, currentVal_array){
        var myPieChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                    labels: ["Bullion", "Cash", "Fixed Deposit", "Other Assets", "Properties", "Stocks", "Mutual Funds"],
                    datasets: [{
                    data: currentVal_array,
                    backgroundColor: ['#00876c', '#63b179', '#aed987', '#ffff9d', '#fcc267', '#ef8250', '#d43d51'],
                    hoverBackgroundColor: ['#00876c', '#58a066', '#98b561', '#dac767', '#e09d4b', '#e06f45', '#d43d51'],
                    hoverBorderColor: "rgba(234, 236, 244, 1)",
                }],
            },
            options: {
                maintainAspectRatio: false,
                tooltips: {
                    backgroundColor: "rgb(255,255,255)",
                    bodyFontColor: "#858796",
                    borderColor: '#dddfeb',
                    borderWidth: 1,
                    xPadding: 15,
                    yPadding: 15,
                    displayColors: false,
                    caretPadding: 10,
                },
                legend: {
                    display: false
                },
                cutoutPercentage: 70,
            },
        });
    };

</script>
