<div class="row" style="position: relative; top: 15px;">
    <div id="mainContent_divSales" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">Net Sales Growth (%)</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_salesChart" class="Net_Sales_Growth_sparkline"></canvas>
            </div>
            <br/>
        </div>
    </div>
    <div id="mainContent_divProfit" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="50" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">Earning Per Share (Rs)</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_profitChart" class="Earning_Per_Share_sparkline"></canvas>
            </div>
            <br/>

        </div>
    </div>
    <div id="mainContent_divROE" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="100" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">Book NAV/Share (Rs)</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_roeChart" class="Book_NAV_Share_sparkline"></canvas>
            </div>
            <br/>
        </div>
    </div>
</div>
<div class="row" style="position: relative; top: 33px;">
    <div id="mainContent_divROCE" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="150" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">EBITDA Margin (%)</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_roceChart" class="EBITDA_Margin_sparkline"></canvas>
            </div>
            <br/>
        </div>
    </div>
    <div id="mainContent_divProfit" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="50" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">PAT Margin (%)</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_profitChart" class="PAT_Marginsparkline"></canvas>
            </div>
            <br/>

        </div>
    </div>
    <div id="mainContent_divROE" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="100" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">ROCE% Trend</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_roeChart" class="ROCE_sparkline"></canvas>
            </div>
            <br/>
        </div>
    </div>
</div>
<div class="row" style="position: relative; top: 52px;">
    <div id="mainContent_divROCE" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="150" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">ROA% Trend</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_roceChart" class="ROA_sparkline"></canvas>
            </div>
            <br/>
        </div>
    </div>
    <div id="mainContent_divProfit" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="50" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">ROE% Trend</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_profitChart" class="ROE_sparkline"></canvas>
            </div>
            <br/>

        </div>
    </div>
    <div id="mainContent_divROE" class="col-12 col-md-4">
        <div class="card cardscreen cardsmall" data-aos="fade-up" data-aos-delay="100" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
            <b><h4 style="padding-left:5%; padding-top:2%; font-weight: 600;">Debt/Equity Ratio</h4></b>
            <div class="sparkchartwrapper d-block w-100">
                <canvas id="mainContent_roeChart" class="Debt_Equity_Ratio_sparkline"></canvas>
            </div>
            <br/>
        </div>
    </div>
</div>
<br/>