<div class="chartjs-wrapper mt-md-5" style='background-color: white; border-radius: 4px; box-shadow: 1px 1px 1px 1px #eee;'>
    <br/>
    <div class="chartjs-size-monitor">
        <div class="chartjs-size-monitor-expand">
            <div class="" id="loading" style="position: relative; left: 46.5%; margin-top:7%; display: block; width: 483px; height: 201px; background-color: white;"><h1>Loading...</h1></div>
        </div>
        <div class="chartjs-size-monitor-shrink">
            <div class=""></div>
        </div>
    </div>
    <div id="chartasd">
        <canvas id="dual-line" height="101" width="483" class="chartjs-render-monitor" style="display: block; width: 483px; height: 201px;"></canvas>
    </div>
</div>