<?php echo Wo_LoadPage('addMFPortfolio/mf_search_container'); ?>
<script>

    async function buyMutualFund(name_, uid){
        const { value: formValues } = await Swal.fire({
            title: 'Buy- ' + name_,
            showCancelButton: true,
            cancelButtonColor: 'red',
            showCloseButton: true,
            width: 'auto',
            html:
               `<table class="table table-hover table-striped">
                   <thead>
                       <tr>
                           <th style="text-align: center;">Transaction Date</th>
                           <th style="text-align: center;">Transaction Price</th>
                           <th style="text-align: center;">Quantity</th>
                           <th style="text-align: center;">Amount</th>
                       </tr>
                   </thead>

                   <tbody id="table_stock_quote_search_body">
                       <tr id=`+ uid +`0 style="height:39px">
                         <td><input id="stock_transaction_date" type="date" name="transaction_date"/></td>
                         <td>
                             <span class="stock_quote_transac_price_div">
                                 <input id="stock_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" onkeyup=changeValues(`+ uid +`0) onchange=changeValues(`+ uid +`0) />
                             </span>
                         </td>
                         <td><input id="stock_qty" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="quantity" style="height:39px;" onkeyup=changeValueAmount(`+ uid +`0) onchange=changeValueAmount(`+ uid +`0) /></td>
                         <td>
                             <span class="stock_quote_transac_price_div">
                                 <input id="stock_transaction_amount" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_amount" style="height:39px;" onkeyup=changeValueQuantity(`+ uid +`0) onchange=changeValueQuantity(`+ uid +`0) />
                             </span>
                         </td>
                       </tr>
                      <jr id=`+ uid +`0stock_notes style="height:39px">
                         <td colspan="7"> <span class="small">Notes:</span> <br> <span> <textarea name="notes" id="notes" rows="1"></textarea> </span> </textarea></td>
                      </tr>
                   </tbody>
               </table>`,

            focusConfirm: false,
            preConfirm: () => {
                stock_quotes_to_add[0] = uid;
                pushStockDataToBackend();
            }
        })
    }
</script>
