<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var mfSearchContainer = $('.stock-search-container');
    var MFSearchResult = $('.stock-search-dropdown-result');
    var mf_quotes_to_add = {};
    var mf_num = 0;

    function Wo_StockSearchResult(query) {
        if (query != '') {
            Wo_progressIconLoader(mfSearchContainer.find('.stock_search'));
            mfSearchContainer.addClass('open');
            $.get(Wo_Ajax_Requests_File(), {f: 'search', s: 'mutual_fund', query: query}, function(data) {
                if (data.status == 200) {
                    if (data.html.length == 0) {
                        MFSearchResult.html('<span class="center-text">' + " <?php echo $wo['lang']['no_result']; ?>" + '<span>');
                    } else {
                       MFSearchResult.html(data.html);
                    }
                }
                Wo_progressIconLoader(mfSearchContainer.find('#stock_search'));
            });
            $(document).click(function() {
                mfSearchContainer.removeClass('open');
            });
        } else {
            mfSearchContainer.removeClass('open');
        }
    }

    function AddStockToTable(fincode, comp_name){
        if (!mf_quotes_to_add.length){
            $('#stock_container').addClass('hidden');
            $('#stock_quote_table_search').removeClass('hidden');
        }
        table_body_data_to_add = `<tr id=`+ fincode + mf_num +` style="height:39px">
                                     <td id="stock_name" class="stock_quote_name_search">` + comp_name + `</td>
                                     <td><input id="stock_transaction_date" type="date" name="transaction_date"/></td>
                                     <td>
                                         <span class="stock_quote_transac_price_div">
                                             <input id="stock_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" onkeyup=changeValueAmount(`+ fincode + mf_num +`) onchange=changeValueAmount(`+ fincode + mf_num +`) />
                                         </span>
                                     </td>
                                     <td><input id="stock_qty" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="quantity" style="height:39px;" onkeyup=changeValueAmount(`+ fincode + mf_num +`) onchange=changeValueAmount(`+ fincode + mf_num +`) /></td>
                                     <td>
                                         <span class="stock_quote_transac_price_div">
                                             <input id="stock_transaction_amount" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_amount" style="height:39px;" onkeyup=changeValueQuantity(`+ fincode + mf_num +`) onchange=changeValueQuantity(`+ fincode + mf_num +`) />
                                         </span>
                                     </td>
                                     <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteStockQuoteFromSearch('`+ fincode + mf_num +`')"></i></td>
                                   </tr>
                                  <tr id=`+ fincode + mf_num +`stock_notes style="height:39px">
                                     <td colspan="7"> <span class="small">Notes:</span> <br> <span> <textarea name="notes" id="notes" rows="1"></textarea> </span> </textarea></td>
                                  </tr>`;

        mf_quotes_to_add[mf_num] = fincode;
        mf_num += 1;

        $('#table_stock_quote_search_body').append(table_body_data_to_add);
    }

    function changeValueAmount(id){
        if ($("#"+id + " #stock_transaction_price").val() != 0){
            amount = $("#"+id + " #stock_qty").val() * $("#"+id + " #stock_transaction_price").val();
            $("#"+id + " #stock_transaction_amount").val(amount);
        }
    }

    function changeValueQuantity(id){
        if ($("#"+id + " #stock_transaction_price").val() != 0){
            quantity = $("#"+id + " #stock_transaction_amount").val() / $("#"+id + " #stock_transaction_price").val();
            $("#"+id + " #stock_qty").val(quantity);
        }
    }

    function deleteStockQuoteFromSearch(id){

        delete mf_quotes_to_add[id.slice(6)];

        if (!(Object.keys(mf_quotes_to_add).length)){
            $('#stock_container').removeClass('hidden');
            $('#stock_quote_table_search').addClass('hidden');
        }

        $("#"+id).remove();
        $("#"+id+"charge").remove();
        $("#"+id+"stock_notes").remove();
    }

    function ajax_call_for_mf(stocks_array_to_send, auto_add_){
        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'add_mutual_funds',
                mf_array: stocks_array_to_send,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                auto_add: auto_add_,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        Swal.fire({
                            icon: 'success',
                            title: 'Mutual Funds Added Successfully!',
                            showConfirmButton: false,
                            timer: 1250,
                            timerProgressBar: true,
                        }).then((result) => {
                            localStorage.removeItem(<?php echo $wo['portfolio_data']['portfolio_id']; ?> + "_portfolio_assets");
                            location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>&tab=overview&content=mutual_funds';
                        })
                    }
                    else if (data['status'] == 401){
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                    }
                    else{
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                        console.log(data['error']);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

    function pushMFDataToBackend(){
        var stocks_array_to_send = new Array();
        var stocks_total_price = 0;
        var earliest_stocks_date = undefined;

        Object.keys(mf_quotes_to_add).forEach(function (id){
            if ($("#"+mf_quotes_to_add[id]+id+" #stock_transaction_date").val() === ""){
                /* alert('Please Enter a Date'); */
                /* $("#"+mf_quotes_to_add[id]+id+" #stock_transaction_date").val(new Date().toDateInputValue()); */
                $("#"+mf_quotes_to_add[id]+id+" #stock_transaction_date").val("NaN");
            }
            /* console.log($("#"+mf_quotes_to_add[id]+id+"charge_").text()) */

            stocks_total_price += parseFloat($("#"+mf_quotes_to_add[id]+id+" #stock_transaction_amount").val());
            if((earliest_stocks_date == undefined) || (parseInt(new Date($("#"+mf_quotes_to_add[id]+id+" #stock_transaction_date").val()).getTime()/1000))) earliest_stocks_date = parseInt(new Date($("#"+mf_quotes_to_add[id]+id+" #stock_transaction_date").val()).getTime()/1000);

            stockInfo = {

                    scheme_code: parseInt(mf_quotes_to_add[id]),
                    mf_transaction_date: parseInt(new Date($("#"+mf_quotes_to_add[id]+id+" #stock_transaction_date").val()).getTime()/1000),
                    mf_transaction_price: parseFloat($("#"+mf_quotes_to_add[id]+id+" #stock_transaction_price").val()),
                    mf_transaction_qty: parseFloat($("#"+mf_quotes_to_add[id]+id+" #stock_qty").val()).toFixed(3),
                    mf_amount: parseFloat($("#"+mf_quotes_to_add[id]+id+" #stock_transaction_amount").val()),
                    note: $("#"+mf_quotes_to_add[id]+id+"stock_notes #notes").val(),

                        };

            stocks_array_to_send.push(stockInfo);
        });

        console.log(stocks_array_to_send);

        /* no_of_unique_stocks = [...new Set(Object.values(mf_quotes_to_add))].length; */
        /* console.log("no_of_unique_stocks"); */
        /* console.log(no_of_unique_stocks); */

        if (stocks_total_price > <?php echo $wo['portfolio_data']['current_value_cash']; ?>){
            Swal.fire({
                title: '<p style="color: red;">Insufficient Cash Available</p>',
                text: 'Cash Available: ₹<?php echo round($wo['portfolio_data']['current_value_cash'], 2); ?> & Transaction Cost: ₹' + stocks_total_price,
                width: 400,
                padding: '3em',
                showCancelButton: false,
                showCloseButton: true,
                showDenyButton: true,
                confirmButtonColor: 'green',
                denyButtonColor: '#236CB0',
                denyButtonText: 'Add Cash Automatically',
                confirmButtonText: 'Add Cash Manually',
                showLoaderOnConfirm: true,
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Add Cash Manually',
                        text: 'Minimum Amount To Add For This Transaction: ₹' + (stocks_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>).toFixed(2),
                        input: 'number',
                        inputAttributes: { min: (stocks_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>), step: 0.0, step: 0.011 },
                        validationMessage: 'Added amount is less than Required amount!',
                        showCloseButton: true,
                        showCancelButton: true,
                        confirmButtonText: 'Add',
                        preConfirm: (amount) => {
                            $.ajax({
                                url: Wo_Ajax_Requests_File(),
                                type: 'GET',
                                dataType: 'json',
                                data: {
                                    f:'add_cash_for_asset',
                                    cash: amount,
                                    portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                                    note: 'Manually added cash for buying Mutual Funds',
                                    date_: earliest_stocks_date,
                                }
                            });
                        },
                        allowOutsideClick: () => !Swal.isLoading()
                    }).then((result) => {
                        if (result.isConfirmed) {
                            ajax_call_for_mf(stocks_array_to_send, '0');
                        }
                    })
                } else if (result.isDenied) {
                    ajax_call_for_mf(stocks_array_to_send, '1');
                }
            })
        } else {
            ajax_call_for_mf(stocks_array_to_send, '0');
        }
    }

</script>
