<li>

    <a href="javascript:void(0);" onclick="AddStockToTable(<?php echo $wo['result']['Scheme Code']; ?>, '<?php echo $wo['result']['Scheme Name']; ?>')">
        <span class="page_title"><?php echo $wo['result']['Scheme Name']; ?></span>
        <div style="color: #4d91ea;">
            <small>
                <?php if (!empty($wo['result']['Scheme Code'])):?>
                <span>Scheme Code: <?php echo $wo['result']['Scheme Code']; ?></span>
                <?php endif; ?>
                <?php if (!empty($wo['result']['ISIN Div Payout/ ISIN Growth']) || !empty($wo['result']['ISIN Div Reinvestment'])):?>
                <span>ISIN: <?php echo $wo['result']['ISIN Div Payout/ ISIN Growth'] . ", " . $wo['result']['ISIN Div Reinvestment']; ?></span>
                <?php endif; ?>
            </small>
        </div>
    </a>

	<div class="clear"></div>

</li>
