<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var StockSearchContainer = $('.stock-search-container');
    var StockSearchResult = $('.stock-search-dropdown-result');
    var stock_quotes_to_add = {};
    var stock_num = 0;

    function Wo_StockSearchResult(query) {
        if (query != '') {
            Wo_progressIconLoader(StockSearchContainer.find('.stock_search'));
            StockSearchContainer.addClass('open');
            $.get(Wo_Ajax_Requests_File(), {f: 'search', s: 'mutual_fund', query: query}, function(data) {
                if (data.status == 200) {
                    if (data.html.length == 0) {
                        StockSearchResult.html('<span class="center-text">' + " <?php echo $wo['lang']['no_result']; ?>" + '<span>');
                    } else {
                        StockSearchResult.html(data.html);
                    }
                }
                Wo_progressIconLoader(StockSearchContainer.find('#stock_search'));
            });
            $(document).click(function() {
                StockSearchContainer.removeClass('open');
            });
        } else {
            StockSearchContainer.removeClass('open');
        }
    }

    function AddStockToTable(fincode, comp_name){
        if (!stock_quotes_to_add.length){
            $('#stock_container').addClass('hidden');
            $('#stock_quote_table_search').removeClass('hidden');
        }
        table_body_data_to_add = `<tr id=`+ fincode + stock_num +` style="height:39px">
                                     <td id="stock_name" class="stock_quote_name_search">` + comp_name + `</td>
                                     <td><input id="stock_transaction_date" type="date" name="transaction_date"/></td>
                                     <td>
                                         <span class="stock_quote_transac_price_div">
                                             <input id="stock_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" onkeyup=changeValueAmount(`+ fincode + stock_num +`) onchange=changeValueAmount(`+ fincode + stock_num +`) />
                                         </span>
                                     </td>
                                     <td><input id="stock_qty" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="quantity" style="height:39px;" onkeyup=changeValueAmount(`+ fincode + stock_num +`) onchange=changeValueAmount(`+ fincode + stock_num +`) /></td>
                                     <td>
                                         <span class="stock_quote_transac_price_div">
                                             <input id="stock_transaction_amount" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_amount" style="height:39px;" onkeyup=changeValueQuantity(`+ fincode + stock_num +`) onchange=changeValueQuantity(`+ fincode + stock_num +`) />
                                         </span>
                                     </td>
                                     <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteStockQuoteFromSearch('`+ fincode + stock_num +`')"></i></td>
                                   </tr>
                                  <tr id=`+ fincode + stock_num +`stock_notes style="height:39px">
                                     <td colspan="7"> <span class="small">Notes:</span> <br> <span> <textarea name="notes" id="notes" rows="1"></textarea> </span> </textarea></td>
                                  </tr>`;

        stock_quotes_to_add[stock_num] = fincode;
        stock_num += 1;

        $('#table_stock_quote_search_body').append(table_body_data_to_add);
    }

    function changeValueAmount(id){
        if ($("#"+id + " #stock_transaction_price").val() != 0){
            amount = $("#"+id + " #stock_qty").val() * $("#"+id + " #stock_transaction_price").val();
            $("#"+id + " #stock_transaction_amount").val(amount);
        }
    }

    function changeValueQuantity(id){
        if ($("#"+id + " #stock_transaction_price").val() != 0){
            quantity = $("#"+id + " #stock_transaction_amount").val() / $("#"+id + " #stock_transaction_price").val();
            $("#"+id + " #stock_qty").val(quantity);
        }
    }

    function deleteStockQuoteFromSearch(id){

        delete stock_quotes_to_add[id.slice(6)];

        if (!(Object.keys(stock_quotes_to_add).length)){
            $('#stock_container').removeClass('hidden');
            $('#stock_quote_table_search').addClass('hidden');
        }

        $("#"+id).remove();
        $("#"+id+"charge").remove();
        $("#"+id+"stock_notes").remove();
    }

    function pushStockDataToBackend(){
        var stock_array_to_send = new Array();
        var no_of_stocks = 0;

        Object.keys(stock_quotes_to_add).forEach(function (id){
            if ($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val() === ""){
                /* alert('Please Enter a Date'); */
                /* $("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val(new Date().toDateInputValue()); */
                $("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val("NaN");
            }
            /* console.log($("#"+stock_quotes_to_add[id]+id+"charge_").text()) */

            stockInfo = {

                    scheme_code: parseInt(stock_quotes_to_add[id]),
                    mf_transaction_date: parseInt(new Date($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_date").val()).getTime()/1000),
                    mf_transaction_price: parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_price").val()),
                    mf_transaction_qty: parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_qty").val()).toFixed(3),
                    mf_amount: parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_transaction_amount").val()),
                    note: $("#"+stock_quotes_to_add[id]+id+"stock_notes #notes").val(),

                        };

            no_of_stocks += parseFloat($("#"+stock_quotes_to_add[id]+id+" #stock_qty").val());
            stock_array_to_send.push(stockInfo);
        });

        console.log(stock_array_to_send);

        /* no_of_unique_stocks = [...new Set(Object.values(stock_quotes_to_add))].length; */
        /* console.log("no_of_unique_stocks"); */
        /* console.log(no_of_unique_stocks); */

        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'add_mutual_funds',
                mf_array: stock_array_to_send,
                no_of_mf: no_of_stocks,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        console.log(data);
                        console.log("done");
                        location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>';
                    }
                    else if (data['status'] == 401){
                        console.log(data['error']);
                        $('#stock_add_errors').text(data['error']);
                    }
                    else{
                        console.log(data);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

</script>

