<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var bullion_to_not_add = new Array();
    var bullion_num = 1;

    function AddBullionToTable(){

        table_body_data_to_add = `<tr id=`+ bullion_num +` style="height:39px">
                                      <td><select name='bullion_type' id='bullion_type' style="width: 6em; height: 2.75em;"><option value="Gold">Gold</option><option value="Silver">Silver</option></select></td>
                                      <td><input id="bullion_transaction_date" type="date" name="transaction_date"/></td>
                                      <td>
                                          <span class="stock_quote_transac_price_div">
                                              <input id="bullion_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" onkeyup=changeBullionValues(`+ bullion_num +` ) onchange=changeBullionValues(`+ bullion_num +` ) />
                                          </span>
                                      </td>
                                      <td><input id="bullion_qty" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_qty" style="height:39px;" onkeyup=changeBullionValues(`+ bullion_num +` ) onchange=changeBullionValues(`+ bullion_num +` ) /></td>
                                      <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteBullion(`+ bullion_num +` )"></i></td>
                                  </tr>
                                  <tr id="`+ bullion_num +`_charge" style="height:39px">
                                      <td>
                                          <span class="small">Charges:</span>
                                          <br>
                                          <span class="stock_quote_transac_price_div">
                                             <input id="bullion_transaction_charge" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_charge" style="height:39px;" onkeyup=changeBullionValues(`+ bullion_num +` ) onchange=changeBullionValues(`+ bullion_num +` ) />
                                          </span>
                                      </td>
                                      <td>
                                          <span class="small">Net Amount:</span>
                                          <br>
                                          <span class="stock_quote_transac_price_div">
                                             <input id="bullion_transaction_net_amount" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_net_amount" style="height:39px;" onkeyup=changeBullionValues(`+ bullion_num +` ) onchange=changeBullionValues(`+ bullion_num +` ) />
                                          </span>
                                      </td>
                                      <td>
                                          <span class="small">Purchased From:</span>
                                          <br>
                                          <span>
                                             <input id="bullion_transaction_purc_fr" type="text" class="stock_quote_transac_price" name="transaction_purc_fr" style="height:39px;"/>
                                          </span>
                                      </td>
                                      <td colspan="2">
                                          <span class="small">Notes:</span>
                                          <br>
                                          <span>
                                              <textarea name="notes" id="notes" rows="1"></textarea>
                                          </span>
                                      </td>
                                  </tr>`


        bullion_num += 1;

        $('#table_bullion_quote_search_body').append(table_body_data_to_add);
    }

    function changeBullionValues(id){
        conversion_metric = ($("#"+id + " #bullion_type").val() == "Gold") ? 10 : 1000;
        amount = parseFloat($("#"+id + " #bullion_transaction_price").val()) * parseFloat($("#"+id + " #bullion_qty").val()) / conversion_metric;
        charge = parseFloat($("#"+id + "_charge #bullion_transaction_charge").val());
        net_amount = amount + charge;
        $("#"+id + "_charge #bullion_transaction_net_amount").val(net_amount);
    }

    function deleteBullion(id){

        bullion_to_not_add.push(id);

        if (bullion_to_not_add.length == bullion_num){

            window.location.replace("<?php echo $wo['portfolio_data']['url'];?>");

        }else{

            $("#"+id).remove();
            $("#"+id+"_charge").remove();

        }
    }

    function ajax_call_for_bullion(bullion_array_to_send, auto_add_){
        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'add_bullion',
                bullion_array: bullion_array_to_send,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                auto_add: auto_add_,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        Swal.fire({
                            icon: 'success',
                            title: 'Bullion Added Successfully!',
                        }).then((result) => {
                            localStorage.removeItem(<?php echo $wo['portfolio_data']['portfolio_id']; ?> + "_portfolio_assets");
                            location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>';
                        })
                    }
                    else if (data['status'] == 401){
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                    }
                    else{
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                        console.log(data['error']);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

    function pushBullionDataToBackend(){
        var bullion_total_price = 0;
        var earliest_bullion_date = undefined;
        var bullion_array_to_send = new Array();

        /* console.log($("#"+bullion_to_add[id]+id+"charge_").text()) */

        for (id = 0; id < bullion_num; id++){
            if (!bullion_to_not_add.includes(id)){

                if ($("#"+id+" #bullion_transaction_date").val() === ""){
                    $("#"+id+" #bullion_transaction_date").val("NaN");
                }

                bullion_total_price += parseFloat($("#"+id+"_charge #bullion_transaction_net_amount").val());
                if((earliest_bullion_date == undefined) || (parseInt(new Date($("#"+id+" #bullion_transaction_date").val()).getTime()/1000) < earliest_bullion_date)) earliest_bullion_date = parseInt(new Date($("#"+id+" #bullion_transaction_date").val()).getTime()/1000);

                bullionInfo = {

                        bullion_type: $('#'+id+' #bullion_type').val(),
                        bullion_transaction_date: parseInt(new Date($("#"+id+" #bullion_transaction_date").val()).getTime()/1000),
                        bullion_transaction_price: parseFloat($("#"+id+" #bullion_transaction_price").val()),
                        bullion_transaction_qty: parseFloat($("#"+id+" #bullion_qty").val()),
                        bullion_charge: parseFloat($("#"+id+"_charge #bullion_transaction_charge").val()),
                        bullion_net_amount: parseFloat($("#"+id+"_charge #bullion_transaction_net_amount").val()),
                        bullion_purchased_from: $("#"+id+"_charge #bullion_transaction_purc_fr").val(),
                        note: $("#"+id+"_charge #notes").val(),

                            };

                bullion_array_to_send.push(bullionInfo);
            }
        }

        if (bullion_total_price > <?php echo $wo['portfolio_data']['current_value_cash']; ?>){
            Swal.fire({
                title: '<p style="color: red;">Insufficient Cash Available</p>',
                text: 'Cash Available: ₹<?php echo $wo['portfolio_data']['current_value_cash']; ?> & Transaction Cost: ₹' + bullion_total_price,
                width: 400,
                padding: '3em',
                showCancelButton: false,
                showCloseButton: true,
                showDenyButton: true,
                confirmButtonColor: 'green',
                denyButtonColor: '#236CB0',
                denyButtonText: 'Add Cash Automatically',
                confirmButtonText: 'Add Cash Manually',
                showLoaderOnConfirm: true,
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Add Cash Manually',
                        text: 'Minimum Amount To Add For This Transaction: ₹' + (bullion_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>),
                        input: 'number',
                        inputAttributes: { min: (parseFloat(bullion_total_price) - <?php echo $wo['portfolio_data']['current_value_cash']; ?>), step: 0.01 },
                        validationMessage: 'Added amount is less than Required amount!',
                        showCloseButton: true,
                        showCancelButton: true,
                        confirmButtonText: 'Add',
                        preConfirm: (amount) => {
                            $.ajax({
                                url: Wo_Ajax_Requests_File(),
                                type: 'GET',
                                dataType: 'json',
                                data: {
                                    f:'add_cash_for_asset',
                                    cash: amount,
                                    portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                                    note: 'Manually added cash for buying Bullion',
                                    date_: earliest_bullion_date,
                                }
                            });
                        },
                        allowOutsideClick: () => !Swal.isLoading()
                    }).then((result) => {
                        if (result.isConfirmed) {
                            ajax_call_for_bullion(bullion_array_to_send, '0');
                        }
                    })
                } else if (result.isDenied) {
                    ajax_call_for_bullion(bullion_array_to_send, '1');
                }
            })
        } else {
            ajax_call_for_bullion(bullion_array_to_send, '0');
        }
    }

</script>
