<!-- JS Pages functions -->
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript">

    Date.prototype.toDateInputValue = (function() {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });

    var property_to_not_add = new Array();
    var property_num = 1;

    function AddPropertyToTable(){

        table_body_data_to_add = `<tr id="`+ property_num +`" style="height:39px">
                                      <td><input id="property_type" type="text" style="height:39px" /></td>
                                      <td><input id="property_transaction_date" type="date" name="transaction_date"/></td>
                                      <td>
                                          <span class="stock_quote_transac_price_div">
                                              <input id="property_transaction_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="transaction_price" style="height:39px;" />
                                          </span>
                                      </td>
                                      <td>
                                          <span class="stock_quote_transac_price_div">
                                              <input id="property_current_price" type="number" min="0" value="0.00" step="any" class="stock_quote_transac_price" name="current_price" style="height:39px;" />
                                          </span>
                                      </td>
                                      <td style="vertical-align: middle;"><i class="fa fa-trash fa-2x stock_search_delete_trash" onclick="deleteProperty(`+ property_num +`)"></i></td>
                                  </tr>

                                  <tr id="`+ property_num +`_charge" style="height:39px">
                                      <td colspan="5">
                                          <span class="small">Notes:</span>
                                          <br>
                                          <span>
                                              <textarea name="notes" id="notes" rows="1"></textarea>
                                          </span>
                                      </td>
                                  </tr>`


        property_num += 1;

        $('#table_property_quote_search_body').append(table_body_data_to_add);
    }

    function deleteProperty(id){

        property_to_not_add.push(id);

        console.log(property_to_not_add);
        console.log(property_to_not_add.length);
        console.log(property_num);

        if (property_to_not_add.length == property_num){

            window.location.replace("<?php echo $wo['portfolio_data']['url'];?>");

        }else{

            $("#"+id).remove();
            $("#"+id+"_charge").remove();

        }
    }

    function ajax_call_for_property(property_array_to_send, auto_add_){
        $.ajax({
            url: Wo_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {
                f:'add_property',
                property_array: property_array_to_send,
                portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                auto_add: auto_add_,
            },
                success: function(data) {
                    if (data['status'] == 200){
                        Swal.fire({
                            icon: 'success',
                            title: 'Property Added Successfully!',
                            showConfirmButton: false,
                            timer: 1250,
                            timerProgressBar: true,
                        }).then((result) => {
                            localStorage.removeItem(<?php echo $wo['portfolio_data']['portfolio_id']; ?> + "_portfolio_assets");
                            location.href = '<?php echo $wo['portfolio_data']['portfolio_url']; ?>&tab=overview&content=property';
                        })
                    }
                    else if (data['status'] == 401){
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                    }
                    else{
                        Swal.fire({
                            icon: 'error',
                            title: data['error'],
                        })
                        console.log(data['error']);
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert("AJAX call failed: " + textStatus + ", " + errorThrown);
                }
        });
    }

    function pushPropertyDataToBackend(){
        var property_total_price = 0;
        var earliest_property_date = undefined;
        var property_array_to_send = new Array();

        for (id = 0; id < property_num; id++){
            if (!property_to_not_add.includes(id)){

                if ($("#"+id+" #property_transaction_date").val() === ""){
                    $("#"+id+" #property_transaction_date").val("NaN");
                }

                property_total_price += parseFloat($("#"+id+" #property_transaction_price").val());
                if((earliest_property_date == undefined) || (parseInt(new Date($("#"+id+" #property_transaction_date").val()).getTime()/1000) < earliest_property_date)) earliest_property_date = parseInt(new Date($("#"+id+" #property_transaction_date").val()).getTime()/1000);

                propertyInfo = {

                        property_type: $('#'+id+' #property_type').val(),
                        property_transaction_date: parseInt(new Date($("#"+id+" #property_transaction_date").val()).getTime()/1000),
                        property_transaction_price: parseFloat($("#"+id+" #property_transaction_price").val()),
                        property_current_price: parseFloat($("#"+id+" #property_current_price").val()),
                        note: $("#"+id+"_charge #notes").val(),

                            };

                property_array_to_send.push(propertyInfo);
            }
        }

        if (property_total_price > <?php echo $wo['portfolio_data']['current_value_cash']; ?>){
            Swal.fire({
                title: '<p style="color: red;">Insufficient Cash Available</p>',
                text: 'Cash Available: ₹<?php echo round($wo['portfolio_data']['current_value_cash'], 2); ?> & Transaction Cost: ₹' + property_total_price,
                width: 400,
                padding: '3em',
                showCancelButton: false,
                showCloseButton: true,
                showDenyButton: true,
                confirmButtonColor: 'green',
                denyButtonColor: '#236CB0',
                denyButtonText: 'Add Cash Automatically',
                confirmButtonText: 'Add Cash Manually',
                showLoaderOnConfirm: true,
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Add Cash Manually',
                        text: 'Minimum Amount To Add For This Transaction: ₹' + (property_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>).toFixed(2),
                        input: 'number',
                        inputAttributes: { min: (property_total_price - <?php echo $wo['portfolio_data']['current_value_cash']; ?>), step: 0.01 },
                        validationMessage: 'Added amount is less than Required amount!',
                        showCloseButton: true,
                        showCancelButton: true,
                        confirmButtonText: 'Add',
                        preConfirm: (amount) => {
                            $.ajax({
                                url: Wo_Ajax_Requests_File(),
                                type: 'GET',
                                dataType: 'json',
                                data: {
                                    f:'add_cash_for_asset',
                                    cash: amount,
                                    portfolio_id: <?php echo $wo['portfolio_data']['portfolio_id'] ?>,
                                    note: 'Manually added cash for buying Property',
                                    date_: earliest_property_date,
                                }
                            });
                        },
                        allowOutsideClick: () => !Swal.isLoading()
                    }).then((result) => {
                        if (result.isConfirmed) {
                            ajax_call_for_property(property_array_to_send, '0');
                        }
                    })
                } else if (result.isDenied) {
                    ajax_call_for_property(property_array_to_send, '1');
                }
            })
        } else {
            ajax_call_for_property(property_array_to_send, '0');
        }
    }

</script>
