<script>

    function mcapWeightageInvested(ctx, fincode_mcap_weightage, type_){

        var options = {
              series: Object.values(fincode_mcap_weightage),
              chart: {
              width: '85%',
              type: (type_ == 'stocks') ? 'donut' : 'pie',
            },
            labels: Object.keys(fincode_mcap_weightage),
            tooltip: {
                enabled: (type_ == 'mutual funds'),
                y: {
                  formatter: function(val) {
                    return (format_rupees(val));
                  }
                },
            },
            plotOptions: {
              pie: {
                donut: {
                    labels: {
                        show: (type_ == 'stocks'),
                        name: {
                            formatter: function(val){return ((val == 'null') ? 'Others' : val);}
                        },
                        value: {
                            formatter: function(val){return ('₹' + parseFloat(val).toFixed(2));}
                        }
                    }
                },
              }
            },
            colors: ['#00876c', '#58a066', '#98b561', '#dac767', '#e09d4b', '#e06f45', '#d43d51'],
            dataLabels: {
              formatter(val, opts) {
                return (val.toFixed(1) + '%');
              }
            },
            animation: {
                enabled: false,
                dynamicAnimation: {
                    enabled: false,
                }
            },
            legend: {
              show: false,
            }
        };
        var chart = new ApexCharts(ctx, options);
        chart.render();

    };

    function mcapWeightageCurrent(ctx, fincode_mcap_weightage, type_){

        var options = {
              series: Object.values(fincode_mcap_weightage),
              chart: {
              width: '85%',
              type: (type_ == 'stocks') ? 'donut' : 'pie',
            },
            labels: Object.keys(fincode_mcap_weightage),
            tooltip: {
                enabled: (type_ == 'mutual funds'),
                y: {
                  formatter: function(val) {
                    return (format_rupees(val));
                  }
                },
            },
            plotOptions: {
              pie: {
                donut: {
                    labels: {
                        show: (type_ == 'stocks'),
                        name: {
                            formatter: function(val){return ((val == 'null') ? 'Others' : val);}
                        },
                        value: {
                            formatter: function(val){return ('₹' + parseFloat(val).toFixed(2));}
                        }
                    }
                },
              }
            },
            colors: ['#00876c', '#58a066', '#98b561', '#dac767', '#e09d4b', '#e06f45', '#d43d51'],
            dataLabels: {
              formatter(val, opts) {
                return (val.toFixed(1) + '%');
              }
            },
            animation: {
                enabled: false,
                dynamicAnimation: {
                    enabled: false,
                }
            },
            legend: {
              show: false,
            }
        };
        var chart = new ApexCharts(ctx, options);
        chart.render();

    };

</script>
