<script>

    function sectorWeightageInvestedCurrent(ctx, fincode_sector_weightage_invested, fincode_sector_weightage_current){

        var sectors_invested = Object.keys(fincode_sector_weightage_invested);
        var weightage_vals_invested = new Array();
        var total_invested = <?php echo $wo['portfolio_data']['stock_invested_value']; ?>;

        for (sector_idx = 0; sector_idx < sectors_invested.length; sector_idx++){
            weightage_vals_invested.push(parseInt((fincode_sector_weightage_invested[sectors_invested[sector_idx]] / total_invested) * 10000) / 100);
        }

        var sectors_current = Object.keys(fincode_sector_weightage_current);
        var weightage_vals_current = new Array();
        var total_current = parseFloat($('#currentVal_stocks_Overview').text());

        for (sector_idx = 0; sector_idx < sectors_current.length; sector_idx++){
            weightage_vals_current.push(parseInt((fincode_sector_weightage_current[sectors_current[sector_idx]] / total_current) * 10000) / 100);
        }

        var options = {
          series: [{
          name: 'Invested Value',
          data: weightage_vals_invested
        }, {
          name: 'Current Value',
          data: weightage_vals_current
        }],
          chart: {
          type: 'bar',
          height: 350
        },
        plotOptions: {
          bar: {
            horizontal: false,
            columnWidth: '55%',
            dataLabels: {
              position: 'top', // top, center, bottom
            },
          },
        },
        dataLabels: {
          enabled: true,
          formatter: function (val, opts) {
            return ('₹' + fincode_sector_weightage_invested[sectors_invested[opts['dataPointIndex']]] + ' (' + val + '%)');
          },
          offsetY: -20,
          style: {
            fontSize: '12px',
            colors: ["#304758"]
          }
        },
        stroke: {
          show: true,
          width: 2,
          colors: ['transparent']
        },
        xaxis: {
          categories: sectors_invested,
          position: 'bottom',
          axisBorder: {
            show: false
          },
          axisTicks: {
            show: false
          },
          tooltip: {
            enabled: false,
          }
        },
        yaxis: {
          axisBorder: {
            show: false
          },
          axisTicks: {
            show: false,
          },
          labels: {
            show: true,
            formatter: function (val) {
              return (val + '%');
            }
          }

        },
        fill: {
          opacity: 1
        },
        tooltip: {
            enabled: false
        }
        };

        var chart = new ApexCharts(ctx, options);
        chart.render();

    };

    function sectorWeightageProfitPer(ctx, fincode_sector_weightage_profit, fincode_sector_weightage_profit_per){

        var options = {
              series: Object.values(fincode_sector_weightage_profit_per),
              chart: {
              width: '64%',
              type: 'donut',
            },
            labels: Object.keys(fincode_sector_weightage_profit_per),
            tooltip: {enabled: false},
            plotOptions: {
              pie: {
                donut: {
                    labels: {
                        show: true,
                        name: {
                        formatter: function(val){return (val + ': ₹' + fincode_sector_weightage_profit[val]);}
                        },
                        value: {
                            formatter: function(val){return ( val + '%');}
                        }
                    }
                },
              }
            },
            colors: ['#00876c', '#58a066', '#98b561', '#dac767', '#e09d4b', '#e06f45', '#d43d51'],
            dataLabels: {
              formatter(val, opts) {
                  /* return (Object.keys(fincode_sector_weightage_profit_per)[opts['seriesIndex']] + ': ₹' + fincode_sector_weightage_profit[Object.keys(fincode_sector_weightage_profit_per)[opts['seriesIndex']]] + ' (' + fincode_sector_weightage_profit_per[Object.keys(fincode_sector_weightage_profit_per)[opts['seriesIndex']]] + '%)'); */
                  return (val.toFixed(1) + '%');
              }
            },
            animation: {
                enabled: false,
                dynamicAnimation: {
                    enabled: false,
                }
            },
            legend: {
              show: true,
              position: 'right'
            }
        };

        var chart = new ApexCharts(ctx, options);
        chart.render();

    };

</script>
